# -*- coding: utf-8 -*-
"""Новые страницы тематического словаря: профессии, одежда, погода,
транспорт, дом, спорт. Регистрирует страницы в build_subpages.PAGES
через make_words_page(). Импорт модуля вызывает register_words()."""

import sys as _sys
if hasattr(_sys.modules.get("__main__"), "PAGES"):
    B = _sys.modules["__main__"]  # build_subpages запущен как скрипт
else:
    import build_subpages as B

WORDS_PROFESSII = [
    ("doctor", "[ˈdɒktə]", "врач", "The doctor helps sick people.", "Врач помогает больным людям."),
    ("nurse", "[nɜːs]", "медсестра", "The nurse works in a hospital.", "Медсестра работает в больнице."),
    ("manager", "[ˈmænɪdʒə]", "менеджер", "The manager works in an office.", "Менеджер работает в офисе."),
    ("policeman", "[pəˈliːsmən]", "полицейский", "The policeman helps people.", "Полицейский помогает людям."),
    ("fireman", "[ˈfaɪəmən]", "пожарный", "The fireman puts out fires.", "Пожарный тушит пожары."),
    ("cook", "[kʊk]", "повар", "The cook makes tasty food.", "Повар готовит вкусную еду."),
    ("driver", "[ˈdraɪvə]", "водитель", "The driver drives a bus.", "Водитель ведёт автобус."),
    ("farmer", "[ˈfɑːmə]", "фермер", "The farmer has many animals.", "У фермера много животных."),
    ("singer", "[ˈsɪŋə]", "певец", "The singer sings beautiful songs.", "Певец поёт красивые песни."),
    ("dancer", "[ˈdɑːnsə]", "танцор", "The dancer dances on the stage.", "Танцор танцует на сцене."),
    ("actor", "[ˈæktə]", "актёр", "The actor plays in the theatre.", "Актёр играет в театре."),
    ("artist", "[ˈɑːtɪst]", "художник", "The artist paints pictures.", "Художник рисует картины."),
    ("writer", "[ˈraɪtə]", "писатель", "The writer writes books.", "Писатель пишет книги."),
    ("vet", "[vet]", "ветеринар", "The vet helps animals.", "Ветеринар лечит животных."),
    ("pilot", "[ˈpaɪlət]", "пилот", "The pilot flies a plane.", "Пилот управляет самолётом."),
    ("builder", "[ˈbɪldə]", "строитель", "The builder builds houses.", "Строитель строит дома."),
    ("dentist", "[ˈdentɪst]", "стоматолог", "The dentist looks at my teeth.", "Стоматолог смотрит мои зубы."),
    ("postman", "[ˈpəʊstmən]", "почтальон", "The postman brings letters.", "Почтальон приносит письма."),
    ("shop assistant", "[ʃɒp əˈsɪstənt]", "продавец", "The shop assistant works in a shop.", "Продавец работает в магазине."),
    ("waiter", "[ˈweɪtə]", "официант", "The waiter brings us food.", "Официант приносит нам еду."),
    ("hairdresser", "[ˈheədresə]", "парикмахер", "The hairdresser cuts my hair.", "Парикмахер стрижёт мои волосы."),
    ("scientist", "[ˈsaɪəntɪst]", "учёный", "The scientist works in a lab.", "Учёный работает в лаборатории."),
    ("engineer", "[endʒɪˈnɪə]", "инженер", "The engineer makes machines.", "Инженер создаёт машины."),
    ("mechanic", "[mɪˈkænɪk]", "механик", "The mechanic fixes cars.", "Механик чинит машины."),
    ("soldier", "[ˈsəʊldʒə]", "солдат", "The soldier is brave.", "Солдат храбрый."),
    ("sailor", "[ˈseɪlə]", "моряк", "The sailor sails a ship.", "Моряк ходит на корабле."),
    ("footballer", "[ˈfʊtbɔːlə]", "футболист", "The footballer scores goals.", "Футболист забивает голы."),
    ("musician", "[mjuːˈzɪʃn]", "музыкант", "The musician plays the piano.", "Музыкант играет на пианино."),
    ("photographer", "[fəˈtɒɡrəfə]", "фотограф", "The photographer takes photos.", "Фотограф делает фотографии."),
    ("astronaut", "[ˈæstrənɔːt]", "космонавт", "The astronaut flies into space.", "Космонавт летит в космос."),
]

WORDS_ODEZHDA = [
    ("T-shirt", "[ˈtiː ʃɜːt]", "футболка", "I wear a white T-shirt.", "Я ношу белую футболку."),
    ("shirt", "[ʃɜːt]", "рубашка", "His shirt is blue.", "Его рубашка синяя."),
    ("trousers", "[ˈtraʊzəz]", "брюки", "These trousers are long.", "Эти брюки длинные."),
    ("jeans", "[dʒiːnz]", "джинсы", "I like my new jeans.", "Мне нравятся мои новые джинсы."),
    ("dress", "[dres]", "платье", "Her dress is beautiful.", "Её платье красивое."),
    ("skirt", "[skɜːt]", "юбка", "The skirt is short.", "Юбка короткая."),
    ("jacket", "[ˈdʒækɪt]", "куртка", "Put on your jacket, it is cold.", "Надень куртку, холодно."),
    ("coat", "[kəʊt]", "пальто", "She wears a warm coat in winter.", "Зимой она носит тёплое пальто."),
    ("hat", "[hæt]", "шляпа, шапка", "The hat is on my head.", "Шапка на моей голове."),
    ("cap", "[kæp]", "кепка", "The boy wears a red cap.", "Мальчик носит красную кепку."),
    ("scarf", "[skɑːf]", "шарф", "This scarf is very warm.", "Этот шарф очень тёплый."),
    ("gloves", "[ɡlʌvz]", "перчатки", "I put on my gloves.", "Я надеваю перчатки."),
    ("socks", "[sɒks]", "носки", "My socks are grey.", "Мои носки серые."),
    ("shoes", "[ʃuːz]", "туфли, обувь", "These shoes are new.", "Эти туфли новые."),
    ("boots", "[buːts]", "сапоги, ботинки", "I wear boots in the rain.", "Я ношу сапоги в дождь."),
    ("trainers", "[ˈtreɪnəz]", "кроссовки", "I run in my trainers.", "Я бегаю в кроссовках."),
    ("sweater", "[ˈswetə]", "свитер", "The sweater is soft.", "Свитер мягкий."),
    ("pyjamas", "[pəˈdʒɑːməz]", "пижама", "I sleep in my pyjamas.", "Я сплю в пижаме."),
    ("shorts", "[ʃɔːts]", "шорты", "He wears shorts in summer.", "Летом он носит шорты."),
    ("blouse", "[blaʊz]", "блузка", "The blouse is white.", "Блузка белая."),
    ("suit", "[suːt]", "костюм", "Dad wears a suit to work.", "Папа носит костюм на работу."),
    ("tie", "[taɪ]", "галстук", "The tie is dark blue.", "Галстук тёмно-синий."),
    ("belt", "[belt]", "ремень", "The belt is black.", "Ремень чёрный."),
    ("raincoat", "[ˈreɪnkəʊt]", "дождевик", "Take your raincoat, it is raining.", "Возьми дождевик, идёт дождь."),
    ("mittens", "[ˈmɪtnz]", "варежки", "My mittens are red.", "Мои варежки красные."),
    ("tights", "[taɪts]", "колготки", "The girl wears tights.", "Девочка носит колготки."),
    ("swimsuit", "[ˈswɪmsuːt]", "купальник", "I swim in a swimsuit.", "Я плаваю в купальнике."),
    ("hoodie", "[ˈhʊdi]", "толстовка с капюшоном", "The hoodie is warm and cosy.", "Толстовка тёплая и уютная."),
    ("uniform", "[ˈjuːnɪfɔːm]", "форма", "Pupils wear a school uniform.", "Ученики носят школьную форму."),
    ("slippers", "[ˈslɪpəz]", "тапочки", "I wear slippers at home.", "Я ношу тапочки дома."),
]

WORDS_POGODA = [
    ("sun", "[sʌn]", "солнце", "The sun shines in the sky.", "Солнце светит в небе."),
    ("rain", "[reɪn]", "дождь", "The rain falls from the clouds.", "Дождь падает из туч."),
    ("snow", "[snəʊ]", "снег", "The snow is white and cold.", "Снег белый и холодный."),
    ("wind", "[wɪnd]", "ветер", "The wind blows the leaves.", "Ветер качает листья."),
    ("cloud", "[klaʊd]", "облако", "The cloud is grey.", "Облако серое."),
    ("sky", "[skaɪ]", "небо", "The sky is blue today.", "Сегодня небо голубое."),
    ("storm", "[stɔːm]", "буря, гроза", "The storm is strong.", "Гроза сильная."),
    ("thunder", "[ˈθʌndə]", "гром", "I hear the thunder.", "Я слышу гром."),
    ("lightning", "[ˈlaɪtnɪŋ]", "молния", "The lightning is bright.", "Молния яркая."),
    ("fog", "[fɒɡ]", "туман", "We cannot see in the fog.", "В тумане ничего не видно."),
    ("ice", "[aɪs]", "лёд", "The ice is slippery.", "Лёд скользкий."),
    ("hail", "[heɪl]", "град", "Hail falls from the sky.", "Град падает с неба."),
    ("hot", "[hɒt]", "жаркий", "It is hot in summer.", "Летом жарко."),
    ("cold", "[kəʊld]", "холодный", "It is cold in winter.", "Зимой холодно."),
    ("warm", "[wɔːm]", "тёплый", "Spring days are warm.", "Весенние дни тёплые."),
    ("cool", "[kuːl]", "прохладный", "Autumn evenings are cool.", "Осенние вечера прохладные."),
    ("sunny", "[ˈsʌni]", "солнечный", "It is a sunny day.", "Сегодня солнечный день."),
    ("rainy", "[ˈreɪni]", "дождливый", "I do not like rainy days.", "Я не люблю дождливые дни."),
    ("snowy", "[ˈsnəʊi]", "снежный", "It is snowy in January.", "В январе снежно."),
    ("windy", "[ˈwɪndi]", "ветреный", "It is windy outside.", "На улице ветрено."),
    ("cloudy", "[ˈklaʊdi]", "облачный", "The day is cloudy.", "День облачный."),
    ("foggy", "[ˈfɒɡi]", "туманный", "It is foggy in the morning.", "Утром туманно."),
    ("weather", "[ˈweðə]", "погода", "What is the weather like today?", "Какая сегодня погода?"),
    ("season", "[ˈsiːzn]", "время года", "My favourite season is summer.", "Моё любимое время года — лето."),
    ("summer", "[ˈsʌmə]", "лето", "We swim in summer.", "Летом мы купаемся."),
    ("winter", "[ˈwɪntə]", "зима", "It snows in winter.", "Зимой идёт снег."),
    ("spring", "[sprɪŋ]", "весна", "Flowers grow in spring.", "Весной растут цветы."),
    ("autumn", "[ˈɔːtəm]", "осень", "Leaves fall in autumn.", "Осенью падают листья."),
    ("temperature", "[ˈtemprətʃə]", "температура", "The temperature is low.", "Температура низкая."),
    ("umbrella", "[ʌmˈbrelə]", "зонт", "Take an umbrella, it may rain.", "Возьми зонт, может пойти дождь."),
]

WORDS_TRANSPORT = [
    ("car", "[kɑː]", "машина", "Dad drives a car.", "Папа водит машину."),
    ("bus", "[bʌs]", "автобус", "I go to school by bus.", "Я еду в школу на автобусе."),
    ("train", "[treɪn]", "поезд", "The train is very fast.", "Поезд очень быстрый."),
    ("plane", "[pleɪn]", "самолёт", "The plane flies high.", "Самолёт летит высоко."),
    ("ship", "[ʃɪp]", "корабль", "The ship sails on the sea.", "Корабль плывёт по морю."),
    ("boat", "[bəʊt]", "лодка", "We row a boat on the lake.", "Мы катаемся на лодке по озеру."),
    ("bicycle", "[ˈbaɪsɪkl]", "велосипед", "I ride my bicycle in the park.", "Я катаюсь на велосипеде в парке."),
    ("motorbike", "[ˈməʊtəbaɪk]", "мотоцикл", "The motorbike is loud.", "Мотоцикл громкий."),
    ("taxi", "[ˈtæksi]", "такси", "We take a taxi home.", "Мы едем домой на такси."),
    ("lorry", "[ˈlɒri]", "грузовик", "The lorry carries food.", "Грузовик везёт еду."),
    ("tram", "[træm]", "трамвай", "The tram goes along the street.", "Трамвай едет по улице."),
    ("underground", "[ˌʌndəˈɡraʊnd]", "метро", "We go by underground in Moscow.", "В Москве мы ездим на метро."),
    ("helicopter", "[ˈhelɪkɒptə]", "вертолёт", "The helicopter flies over the city.", "Вертолёт летит над городом."),
    ("rocket", "[ˈrɒkɪt]", "ракета", "The rocket flies to the Moon.", "Ракета летит на Луну."),
    ("scooter", "[ˈskuːtə]", "самокат", "I ride my scooter after school.", "Я катаюсь на самокате после школы."),
    ("ambulance", "[ˈæmbjələns]", "скорая помощь", "The ambulance helps sick people.", "Скорая помощь помогает больным."),
    ("fire engine", "[ˈfaɪə endʒɪn]", "пожарная машина", "The fire engine is red.", "Пожарная машина красная."),
    ("police car", "[pəˈliːs kɑː]", "полицейская машина", "The police car is fast.", "Полицейская машина быстрая."),
    ("van", "[væn]", "фургон", "The van brings our food.", "Фургон привозит нашу еду."),
    ("platform", "[ˈplætfɔːm]", "платформа", "We wait on the platform.", "Мы ждём на платформе."),
    ("ferry", "[ˈferi]", "паром", "The ferry crosses the river.", "Паром переправляется через реку."),
    ("yacht", "[jɒt]", "яхта", "The yacht is white.", "Яхта белая."),
    ("sledge", "[sledʒ]", "санки", "Children ride sledges in winter.", "Зимой дети катаются на санках."),
    ("hot-air balloon", "[hɒt eə bəˈluːn]", "воздушный шар", "The hot-air balloon rises up.", "Воздушный шар поднимается вверх."),
    ("wheel", "[wiːl]", "колесо", "A car has four wheels.", "У машины четыре колеса."),
    ("ticket", "[ˈtɪkɪt]", "билет", "I buy a ticket for the train.", "Я покупаю билет на поезд."),
    ("station", "[ˈsteɪʃn]", "станция", "The train stops at the station.", "Поезд останавливается на станции."),
    ("airport", "[ˈeəpɔːt]", "аэропорт", "Planes take off at the airport.", "Самолёты взлетают в аэропорту."),
    ("road", "[rəʊd]", "дорога", "The road is long.", "Дорога длинная."),
    ("passenger", "[ˈpæsɪndʒə]", "пассажир", "The passenger buys a ticket.", "Пассажир покупает билет."),
]

WORDS_DOM = [
    ("house", "[haʊs]", "дом", "Our house is big.", "Наш дом большой."),
    ("flat", "[flæt]", "квартира", "We live in a flat.", "Мы живём в квартире."),
    ("room", "[ruːm]", "комната", "My room is cosy.", "Моя комната уютная."),
    ("kitchen", "[ˈkɪtʃɪn]", "кухня", "Mum cooks in the kitchen.", "Мама готовит на кухне."),
    ("bedroom", "[ˈbedruːm]", "спальня", "I sleep in my bedroom.", "Я сплю в своей спальне."),
    ("bathroom", "[ˈbɑːθruːm]", "ванная", "I wash my hands in the bathroom.", "Я мою руки в ванной."),
    ("living room", "[ˈlɪvɪŋ ruːm]", "гостиная", "We watch TV in the living room.", "Мы смотрим телевизор в гостиной."),
    ("hall", "[hɔːl]", "прихожая", "Leave your shoes in the hall.", "Оставь обувь в прихожей."),
    ("window", "[ˈwɪndəʊ]", "окно", "Open the window, please.", "Открой окно, пожалуйста."),
    ("door", "[dɔː]", "дверь", "Close the door.", "Закрой дверь."),
    ("wall", "[wɔːl]", "стена", "A picture hangs on the wall.", "Картина висит на стене."),
    ("floor", "[flɔː]", "пол", "The floor is clean.", "Пол чистый."),
    ("roof", "[ruːf]", "крыша", "The roof is red.", "Крыша красная."),
    ("stairs", "[steəz]", "лестница", "Go up the stairs.", "Поднимись по лестнице."),
    ("garden", "[ˈɡɑːdn]", "сад", "Flowers grow in the garden.", "В саду растут цветы."),
    ("table", "[ˈteɪbl]", "стол", "The book is on the table.", "Книга лежит на столе."),
    ("sofa", "[ˈsəʊfə]", "диван", "The cat sleeps on the sofa.", "Кошка спит на диване."),
    ("armchair", "[ˈɑːmtʃeə]", "кресло", "Grandpa sits in the armchair.", "Дедушка сидит в кресле."),
    ("bed", "[bed]", "кровать", "I go to bed at nine.", "Я ложусь спать в девять."),
    ("lamp", "[læmp]", "лампа", "Turn on the lamp.", "Включи лампу."),
    ("fridge", "[frɪdʒ]", "холодильник", "The milk is in the fridge.", "Молоко в холодильнике."),
    ("cooker", "[ˈkʊkə]", "плита", "Mum cooks soup on the cooker.", "Мама варит суп на плите."),
    ("cupboard", "[ˈkʌbəd]", "шкаф (кухонный)", "The cups are in the cupboard.", "Чашки в шкафу."),
    ("wardrobe", "[ˈwɔːdrəʊb]", "шкаф для одежды", "My clothes are in the wardrobe.", "Моя одежда в шкафу."),
    ("mirror", "[ˈmɪrə]", "зеркало", "I look in the mirror.", "Я смотрю в зеркало."),
    ("carpet", "[ˈkɑːpɪt]", "ковёр", "The carpet is soft.", "Ковёр мягкий."),
    ("curtain", "[ˈkɜːtn]", "штора", "Close the curtains, please.", "Закрой шторы, пожалуйста."),
    ("shelf", "[ʃelf]", "полка", "Books are on the shelf.", "Книги стоят на полке."),
    ("clock", "[klɒk]", "часы", "The clock is on the wall.", "Часы висят на стене."),
    ("balcony", "[ˈbælkəni]", "балкон", "Flowers grow on our balcony.", "На нашем балконе растут цветы."),
]

WORDS_SPORT = [
    ("sport", "[spɔːt]", "спорт", "Sport is good for health.", "Спорт полезен для здоровья."),
    ("football", "[ˈfʊtbɔːl]", "футбол", "We play football on Saturdays.", "Мы играем в футбол по субботам."),
    ("basketball", "[ˈbɑːskɪtbɔːl]", "баскетбол", "Basketball is a tall game.", "В баскетбол играют высокие."),
    ("volleyball", "[ˈvɒlibɔːl]", "волейбол", "We play volleyball on the beach.", "Мы играем в волейбол на пляже."),
    ("tennis", "[ˈtenɪs]", "теннис", "She plays tennis well.", "Она хорошо играет в теннис."),
    ("swimming", "[ˈswɪmɪŋ]", "плавание", "Swimming is fun.", "Плавание — это весело."),
    ("running", "[ˈrʌnɪŋ]", "бег", "Running in the morning is nice.", "Бегать по утрам приятно."),
    ("hockey", "[ˈhɒki]", "хоккей", "Hockey is popular in Russia.", "Хоккей популярен в России."),
    ("skating", "[ˈskeɪtɪŋ]", "катание на коньках", "We go skating in winter.", "Зимой мы катаемся на коньках."),
    ("skiing", "[ˈskiːɪŋ]", "катание на лыжах", "I like skiing in the mountains.", "Мне нравится кататься на лыжах в горах."),
    ("snowboard", "[ˈsnəʊbɔːd]", "сноуборд", "He rides a snowboard fast.", "Он быстро катается на сноуборде."),
    ("gymnastics", "[dʒɪmˈnæstɪks]", "гимнастика", "She does gymnastics every day.", "Она занимается гимнастикой каждый день."),
    ("karate", "[kəˈrɑːti]", "карате", "My brother does karate.", "Мой брат занимается карате."),
    ("boxing", "[ˈbɒksɪŋ]", "бокс", "Boxing is a hard sport.", "Бокс — тяжёлый спорт."),
    ("cycling", "[ˈsaɪklɪŋ]", "велоспорт", "Cycling is good exercise.", "Езда на велосипеде — хорошее упражнение."),
    ("dancing", "[ˈdɑːnsɪŋ]", "танцы", "Dancing makes me happy.", "Танцы делают меня счастливой."),
    ("ball", "[bɔːl]", "мяч", "Kick the ball to me.", "Ударь мяч мне."),
    ("team", "[tiːm]", "команда", "Our team wins the game.", "Наша команда выигрывает матч."),
    ("player", "[ˈpleɪə]", "игрок", "The player runs fast.", "Игрок бегает быстро."),
    ("coach", "[kəʊtʃ]", "тренер", "The coach helps the team.", "Тренер помогает команде."),
    ("match", "[mætʃ]", "матч", "The match starts at six.", "Матч начинается в шесть."),
    ("game", "[ɡeɪm]", "игра", "This game is interesting.", "Эта игра интересная."),
    ("goal", "[ɡəʊl]", "гол", "He scores a goal!", "Он забивает гол!"),
    ("win", "[wɪn]", "побеждать", "I want to win the race.", "Я хочу выиграть гонку."),
    ("lose", "[luːz]", "проигрывать", "It is OK to lose sometimes.", "Иногда проигрывать — это нормально."),
    ("run", "[rʌn]", "бегать", "I run in the park.", "Я бегаю в парке."),
    ("jump", "[dʒʌmp]", "прыгать", "The children jump high.", "Дети прыгают высоко."),
    ("swim", "[swɪm]", "плавать", "Fish swim in the river.", "Рыбы плавают в реке."),
    ("race", "[reɪs]", "гонка, забег", "The race is long.", "Забег длинный."),
    ("champion", "[ˈtʃæmpiən]", "чемпион", "She is the school champion.", "Она чемпионка школы."),
]

NEW_TOPICS = [
    ("professii", "Профессии"),
    ("odezhda", "Одежда"),
    ("pogoda", "Погода"),
    ("transport", "Транспорт"),
    ("dom", "Дом"),
    ("sport", "Спорт"),
]


def register_words():
    B.make_words_page(
        "page_english_words_professii.html", "english-words/professii", "professii",
        "Профессии", "профессий",
        'Английские слова по теме <span class="fxb-accent">«Профессии»</span>',
        "30 слов по теме «Профессии» с транскрипцией, переводом и примерами: кем работают люди и как это сказать по-английски. Уровень A1 для детей и родителей.",
        "Английские слова по теме «Профессии» с транскрипцией и переводом: 30 слов уровня A1 с примерами предложений. Словарь для детей и родителей — бесплатно, от школы Фоксинбург.",
        WORDS_PROFESSII,
        "linear-gradient(135deg,#1a1630 0%,#3b2a63 55%,#6d3fb8 100%)",
        [("/mladshie-shkolniki", "Младшим школьникам"), ("/podrostki", "Подросткам"), ("/doshkolniki", "Дошкольникам")],
    )
    B.make_words_page(
        "page_english_words_odezhda.html", "english-words/odezhda", "odezhda",
        "Одежда", "одежды",
        'Английские слова по теме <span class="fxb-accent">«Одежда»</span>',
        "30 слов по теме «Одежда» с транскрипцией, переводом и примерами: весь гардероб по-английски для уровня A1 — детям и родителям.",
        "Английские слова по теме «Одежда» с транскрипцией и переводом: 30 слов уровня A1 с примерами предложений. Словарь для детей и родителей — бесплатно, от школы Фоксинбург.",
        WORDS_ODEZHDA,
        "linear-gradient(135deg,#2e1226 0%,#5c1f4a 55%,#93396f 100%)",
        [("/doshkolniki", "Дошкольникам"), ("/mladshie-shkolniki", "Младшим школьникам")],
    )
    B.make_words_page(
        "page_english_words_pogoda.html", "english-words/pogoda", "pogoda",
        "Погода", "погоды",
        'Английские слова по теме <span class="fxb-accent">«Погода»</span>',
        "30 слов по теме «Погода» с транскрипцией, переводом и примерами: учимся описывать день за окном по-английски. Уровень A1.",
        "Английские слова по теме «Погода» с транскрипцией и переводом: 30 слов уровня A1 с примерами предложений. Словарь для детей и родителей — бесплатно, от школы Фоксинбург.",
        WORDS_POGODA,
        "linear-gradient(135deg,#0f2030 0%,#1f4870 55%,#3d7ab8 100%)",
        [("/doshkolniki", "Дошкольникам"), ("/mladshie-shkolniki", "Младшим школьникам")],
    )
    B.make_words_page(
        "page_english_words_transport.html", "english-words/transport", "transport",
        "Транспорт", "транспорта",
        'Английские слова по теме <span class="fxb-accent">«Транспорт»</span>',
        "30 слов по теме «Транспорт» с транскрипцией, переводом и примерами: от велосипеда до ракеты по-английски. Уровень A1.",
        "Английские слова по теме «Транспорт» с транскрипцией и переводом: 30 слов уровня A1 с примерами предложений. Словарь для детей и родителей — бесплатно, от школы Фоксинбург.",
        WORDS_TRANSPORT,
        "linear-gradient(135deg,#13251c 0%,#2a5443 55%,#4b8a68 100%)",
        [("/doshkolniki", "Дошкольникам"), ("/mladshie-shkolniki", "Младшим школьникам")],
    )
    B.make_words_page(
        "page_english_words_dom.html", "english-words/dom", "dom",
        "Дом", "дома",
        'Английские слова по теме <span class="fxb-accent">«Дом»</span>',
        "30 слов по теме «Дом» с транскрипцией, переводом и примерами: комнаты и мебель по-английски для уровня A1 — детям и родителям.",
        "Английские слова по теме «Дом» с транскрипцией и переводом: 30 слов уровня A1 с примерами предложений. Словарь для детей и родителей — бесплатно, от школы Фоксинбург.",
        WORDS_DOM,
        "linear-gradient(135deg,#2a1a12 0%,#59412a 55%,#8f6b42 100%)",
        [("/doshkolniki", "Дошкольникам"), ("/mladshie-shkolniki", "Младшим школьникам")],
    )
    B.make_words_page(
        "page_english_words_sport.html", "english-words/sport", "sport",
        "Спорт", "спорта",
        'Английские слова по теме <span class="fxb-accent">«Спорт»</span>',
        "30 слов по теме «Спорт» с транскрипцией, переводом и примерами: виды спорта и игры по-английски для уровня A1.",
        "Английские слова по теме «Спорт» с транскрипцией и переводом: 30 слов уровня A1 с примерами предложений. Словарь для детей и родителей — бесплатно, от школы Фоксинбург.",
        WORDS_SPORT,
        "linear-gradient(135deg,#101a2e 0%,#243b6e 55%,#4666c0 100%)",
        [("/mladshie-shkolniki", "Младшим школьникам"), ("/podrostki", "Подросткам")],
    )


register_words()
