"""1 класс: устная линия Фоксинбурга.

Карта тем как у школьного курса 1 класса (семья → школа → комната → питомцы → еда → игры).
Тексты, песни и упражнения учебников не копируем: Фокси учит своими словами,
как учитель на занятии. Потом в пути идёт phonics (чтение).
"""
from __future__ import annotations

import re

from .word_library import image_path, phrase_for, teach_line

BOOK = "starter-oral"
BOOK_RU = "1 класс · Foxy учит говорить"


def tokenize_en(text: str) -> list[str]:
    return [t for t in re.findall(r"[A-Za-z]+(?:'[A-Za-z]+)?|[.,!?]", text) if t]


def _w(en: str, ipa: str, ru: str) -> dict:
    return {
        "en": en,
        "ipa": ipa,
        "ru": ru,
        "image": image_path(en),
        "teach_ru": teach_line(en, ru),
        "example_en": phrase_for(en, ru)[0],
        "example_ru": phrase_for(en, ru)[1],
    }


def _c(
    title: str,
    body: str,
    steps: list[str],
    *,
    foxi: str,
    speak: str = "",
    visual: str = "foxi-hello",
    example_en: str = "",
    example_ru: str = "",
    image: str = "",
) -> dict:
    return {
        "title_ru": title,
        "body_ru": body,
        "steps": steps,
        "visual_id": visual,
        "gpc": "",
        "sound": "",
        "speak_sound": speak,
        "speak": speak,
        "audio": "",
        "example_en": example_en,
        "example_ru": example_ru,
        "image": image,
        "foxi_line": foxi,
    }


def _teach(
    *,
    hello: str,
    goal: str,
    mouth: str,
    when: str,
    trap: str,
    together: str,
    extra_title: str,
    extra_body: str,
    extra_steps: list[str],
    speak: str,
    demo_en: str,
    demo_ru: str,
    first: dict,
) -> list[dict]:
    img = first.get("image", "")
    word_en = first.get("en") or ""
    trap_title = extra_title.strip() if extra_title else "Типичные ошибки"
    trap_steps = [
        extra_steps[-1] if extra_steps else "Сравни с образцом",
        "Повтори правильный вариант вслух",
        "Потом переходи к словам",
    ]
    return [
        _c(
            "1 · Цель урока",
            f"{hello} {goal} Когда так говорят: {when} "
            f"Сегодня не список слов из словаря, а живой кусок урока: смысл → звук → фраза.",
            ["Прочитай цель", "Представь ситуацию", "Дальше — рот и звук"],
            foxi=hello,
            speak="",
            visual="foxi-hello",
            example_en=demo_en,
            example_ru=demo_ru,
        ),
        _c(
            "2 · Произношение",
            f"{mouth} "
            f"Слушай образец. Повтори три раза: шёпотом, обычным голосом, громко. "
            f"Смотри на рот: губы, язык, зубки. Русскими буквами слово не читай.",
            ["Слушай слово", "Скажи медленно", "Скажи чуть быстрее"],
            foxi="Повтори за мной. За кривой звук сердца не тратим — только учимся.",
            speak=word_en or speak,
            example_en=word_en or demo_en,
            example_ru="",
            image=img,
            visual="",
        ),
        _c(
            "3 · Фраза и диалог",
            f"{together} {extra_title}. {extra_body} "
            f"Фразу говори целиком, как в классе у доски, а не по одному слову.",
            extra_steps or ["Слушай фразу", "Повтори целиком", "Скажи как будто учителю"],
            foxi="Три раза: со мной, сам, как будто маме.",
            speak=demo_en or speak,
            example_en=demo_en,
            example_ru=demo_ru,
            image=img,
            visual="foxi-hello",
        ),
        _c(
            f"4 · {trap_title}",
            f"{trap} Это ошибка именно этого урока, не общая фраза «не зубри перевод». "
            f"Сравни свой рот с образцом и исправь до заданий.",
            trap_steps,
            foxi=trap,
            speak="",
            example_en="",
            example_ru="",
            visual="",
            image=img,
        ),
    ]


def _lesson(title: str, words: list[tuple], phrases: list[tuple], cards: list[dict]) -> dict:
    wds = [_w(*row) for row in words]
    return {
        "title_ru": title,
        "mode": "oral",
        "gpc": "",
        "sound": "",
        "cards": cards,
        "words": wds,
        "phrases": phrases,
    }


def _unit(uid: str, title: str, topic: str, goal: str, accent: str, lessons: list[dict]) -> dict:
    spots = [ls["title_ru"] for ls in lessons]
    words, phrases, seen = [], [], set()
    for ls in lessons:
        for w in ls["words"]:
            if w["en"] not in seen:
                seen.add(w["en"])
                words.append((w["en"], w["ipa"], w["ru"], w["en"], w["ru"]))
        phrases.extend(ls["phrases"])
    return {
        "id": uid,
        "book": BOOK,
        "book_ru": BOOK_RU,
        "place_ru": title,
        "topic_ru": topic,
        "goal_ru": goal,
        "accent": accent,
        "spots": spots,
        "has_checkpoint": True,
        "checkpoint_ru": f"Проверка: {topic}",
        "grammar": lessons[-1]["cards"][1:3],
        "theory": [ls["cards"][1] for ls in lessons],
        "words": words,
        "phrases": phrases,
        "lessons": lessons,
    }


def _L(title, words, phrases, **teach_kw):
    first = _w(*words[0])
    return _lesson(title, words, phrases, _teach(first=first, **teach_kw))


COURSE = [
    _unit(
        "family", "Моя семья", "Знакомимся, называем семью, чувства и цвета",
        "Поздороваться, сказать как зовут, назвать маму и папу, цвет и настроение.",
        "#3a2953",
        [
            _L(
                "Привет!",
                [("hello", "həˈləʊ", "привет"), ("hi", "haɪ", "привет (коротко)"),
                 ("name", "neɪm", "имя"), ("fox", "fɒks", "лиса"),
                 ("yes", "jes", "да"), ("no", "nəʊ", "нет")],
                [("Hello!", "Привет!"), ("Hi!", "Привет!"),
                 ("I am Foxy.", "Я Foxy."), ("What is your name?", "Как тебя зовут?"),
                 ("My name is Foxy.", "Меня зовут Фокси.")],
                hello="На уроке сначала здороваются. Не молча открывают тетрадь — говорят Hello.",
                goal="Выучим Hello и Hi. Это два приветствия. Hi короче, как «прив». Hello чуть вежливее.",
                mouth="Hello: хе-ЛОУ. Удар в конце. Губы округли на «ou». Не «хеллоу» по-русски с твёрдым Л.",
                when="Когда видишь человека (или Фокси на экране). Утром, в школе, в игре — одно и то же слово.",
                trap="Дети говорят «хэллоу» как в мультике слишком растянуто. Коротко: he-LOU. И смотри в «глаза».",
                together="Скажи мне Hello. Потом Hi. Потом I am … и своё имя по-русски можно, английское имя — если есть.",
                extra_title="Диалог учителя и ученика",
                extra_body="Учитель: Hello! Ученик: Hello! Учитель: I am Foxy. Ученик: повторяет I am и своё имя. "
                           "Если забыл — не стыдно: ещё раз со мной. Имя по-английски не обязательно сегодня.",
                extra_steps=["Hello мне", "Hello тебе", "I am + имя"],
                speak="Hello!", demo_en="Hello!", demo_ru="Привет!",
            ),
            _L(
                "Я Foxy",
                [("i", "aɪ", "я"), ("am", "æm", "есть / являюсь"),
                 ("foxy", "ˈfɒksi", "Foxy"), ("you", "juː", "ты"),
                 ("yes", "jes", "да"), ("no", "nəʊ", "нет")],
                [("I am Foxy.", "Я Foxy."), ("I am a fox.", "Я лиса."),
                 ("You are a kid.", "Ты ребёнок."), ("Yes, I am.", "Да."),
                 ("No, I am not.", "Нет, я не …")],
                hello="В английском «я» — всегда I с большой буквы. Даже в середине мысли в тетради потом так пишут.",
                goal="Склеиваем I + am. Это как «я есть». По-русски «есть» часто прячем: «я Фокси». По-английски am нужно.",
                mouth="I звучит как «ай». am — короткое «эм» с открытым ртом, не «эйм».",
                when="Когда представляешься: I am … Когда отвечаешь «это я»: Yes, I am.",
                trap="Калька «Я есть Foxy» смешная по-русски, но по-английски I am Foxy — норма. Не пропускай am.",
                together="I am Foxy. Теперь I am и твоё имя. Громко.",
                extra_title="Почему I всегда большое",
                extra_body="Это правило вежливости к себе в письме. Сегодня ты только говоришь, но запомни картинку: "
                           "одинокая палочка I — всегда высокая. you — «ты», you are — «ты есть».",
                extra_steps=["Скажи I", "Добавь am", "Назови себя"],
                speak="I am Foxy.", demo_en="I am Foxy.", demo_ru="Я Foxy.",
            ),
            _L(
                "Мама и папа",
                [("mum", "mʌm", "мама"), ("dad", "dæd", "папа"),
                 ("sister", "ˈsɪstə", "сестра"), ("brother", "ˈbrʌðə", "брат"),
                 ("baby", "ˈbeɪbi", "малыш"), ("family", "ˈfæmɪli", "семья")],
                [("This is mum.", "Это мама."), ("This is dad.", "Это папа."),
                 ("This is my family.", "Это моя семья."), ("I love mum.", "Я люблю маму."),
                 ("Mum and dad.", "Мама и папа.")],
                hello="Семья — первые люди, которых называют на новом языке. Не животных, не буквы — людей рядом.",
                goal="mum, dad, sister, brother, baby. my значит «моя/мой». This is — «это».",
                mouth="mum: губы вместе, нос гудит. dad: кончик языка к бугоркам, с голосом. brother: th — язык к зубам, не «з».",
                when="Показываешь фото или человека: This is mum. Не This mum без is.",
                trap="«мама» на английском не mama в школе этого курса — говорим mum. dad не «дэд» злодей, а тёплый dad.",
                together="This is mum. This is dad. This is my family.",
                extra_title="This is — учительский жест",
                extra_body="Указательный палец (или взгляд) + This is + кто. Так учитель показывает картинку в классе. "
                           "my family — вся кучка вместе. Если брата нет — говори This is mum and dad.",
                extra_steps=["This is", "mum / dad", "my family"],
                speak="This is mum.", demo_en="This is mum.", demo_ru="Это мама.",
            ),
            _L(
                "Я радуюсь",
                [("happy", "ˈhæpi", "радостный"), ("sad", "sæd", "грустный"),
                 ("smile", "smaɪl", "улыбка"), ("cry", "kraɪ", "плакать"),
                 ("good", "ɡʊd", "хороший"), ("bad", "bæd", "плохой")],
                [("I am happy.", "Я радуюсь."), ("I am sad.", "Мне грустно."),
                 ("I smile.", "Я улыбаюсь."), ("Are you happy?", "Ты рад?"),
                 ("Yes, I am happy.", "Да, я рад.")],
                hello="Чувства — тоже слова. Учитель спрашивает не только «как зовут», но «как ты».",
                goal="I am happy / I am sad. Та же схема I am, новое слово после неё.",
                mouth="happy: ха-пи, короткое a как в cat. sad: открытый рот, не «сэд» как «седой».",
                when="На вопрос How are you? позже. Сегодня — просто сказать про себя после игры или если упал.",
                trap="happy не «хэппи» с русским П взрывом. Мягко. И не путай sad и said.",
                together="I am happy. Улыбнись. I am sad. Грустное лицо. Так тело помогает памяти.",
                extra_title="Вопрос учителя",
                extra_body="Are you happy? — «ты рад?». Ответ: Yes, I am. или No, I am sad. "
                           "Не отвечай «да» по-русски на английский вопрос — сегодня тренируем Yes.",
                extra_steps=["I am + чувство", "Yes / No", "Лицо помогает"],
                speak="I am happy.", demo_en="I am happy.", demo_ru="Я радуюсь.",
            ),
            _L(
                "Цвета",
                [("red", "red", "красный"), ("blue", "bluː", "синий"),
                 ("green", "ɡriːn", "зелёный"), ("yellow", "ˈjeləʊ", "жёлтый"),
                 ("black", "blæk", "чёрный"), ("white", "waɪt", "белый")],
                [("It is red.", "Это красное."), ("A red fox.", "Рыжая/красная лиса."),
                 ("I like blue.", "Мне нравится синий."), ("Yellow and green.", "Жёлтый и зелёный."),
                 ("What colour?", "Какой цвет?")],
                hello="Цвет — якорь. Ребёнок видит, учитель называет, ученик повторяет. Не учим радугу списком без глаз.",
                goal="Шесть цветов. Фраза It is + цвет. like — «нравится».",
                mouth="red: короткий e как в bed. blue: губы трубочкой, долгое у. yellow: йе-лоу, не «еллоу» с русским Е.",
                when="Показываешь карандаш, носок, лису Фокси. What colour? — вопрос учителя.",
                trap="fox часто рыжий, по-английски всё равно red fox в детской речи. white: без русского «х» в начале.",
                together="It is red. It is blue. I like yellow.",
                extra_title="Игра учителя «покажи цвет»",
                extra_body="Я говорю red — ты ищешь красное в комнате или на экране. Потом ты говоришь цвет, я подтверждаю. "
                           "Так слово приклеивается к вещи, а не к строчке в учебнике.",
                extra_steps=["Услышать цвет", "Найти глазами", "Сказать It is …"],
                speak="It is red.", demo_en="It is red.", demo_ru="Это красное.",
            ),
            _L(
                "Я знаю семью",
                [("hello", "həˈləʊ", "привет"), ("mum", "mʌm", "мама"),
                 ("dad", "dæd", "папа"), ("happy", "ˈhæpi", "радостный"),
                 ("red", "red", "красный"), ("family", "ˈfæmɪli", "семья")],
                [("Hello, mum!", "Привет, мама!"), ("This is dad.", "Это папа."),
                 ("I am happy.", "Я радуюсь."), ("My family.", "Моя семья."),
                 ("I like red.", "Мне нравится красный.")],
                hello="Урок-проверка, как «я знаю» в конце модуля. Я не ставлю двойку. Я смотрю, что уже во рту.",
                goal="Собрать привет + семья + чувство + цвет в короткие фразы.",
                mouth="Не торопись. Каждая фраза — отдельный выдох.",
                when="Можно дома: Hello, mum! за завтраком. Это и есть домашнее задание без тетради.",
                trap="Не склеивай всё в кашу Helloiamfoxi. Паузы — часть речи.",
                together="Hello! This is my family. I am happy.",
                extra_title="Мини-сцена",
                extra_body="1) Поздоровайся. 2) Покажи маму или папу. 3) Скажи, рад ты или нет. 4) Назови любимый цвет. "
                           "Я, Фокси, хлопаю, если все четыре шага были.",
                extra_steps=["Hello", "This is …", "I am happy/sad", "цвет"],
                speak="Hello, mum!", demo_en="Hello, mum!", demo_ru="Привет, мама!",
            ),
        ],
    ),
    _unit(
        "school", "Моя школа", "Числа, портфель, где лежит вещь",
        "Считать до десяти, назвать школьные вещи, сказать in / on.",
        "#ee7349",
        [
            _L(
                "Числа 1–5",
                [("one", "wʌn", "один"), ("two", "tuː", "два"),
                 ("three", "θriː", "три"), ("four", "fɔː", "четыре"),
                 ("five", "faɪv", "пять"), ("number", "ˈnʌmbə", "число")],
                [("One, two, three.", "Раз, два, три."), ("I see two.", "Я вижу два."),
                 ("Number one.", "Номер один."), ("Four and five.", "Четыре и пять."),
                 ("Count with me.", "Считай со мной.")],
                hello="Счёт — хором. Учитель ведёт рукой, дети говорят. Сегодня рука — твоя, голос — со мной.",
                goal="one two three four five. Не цифры «как в математике», а слова.",
                mouth="three: язык к зубам, воздух, не «сри» и не «фри». two: как «ту», не «тво».",
                when="Считаем лис, карандаши, хлопки. Count with me — команда учителя.",
                trap="three самое трудное. Если не выходит th — всё равно пытайся, не заменяй на «три» по-русски.",
                together="One. Two. Three. Four. Five. Ещё круг.",
                extra_title="Пальцы",
                extra_body="Покажи пальцы и назови. Потом спрячь руки и назови по памяти. Так учитель проверяет, "
                           "слово это или только жест.",
                extra_steps=["Хор", "Пальцы", "Без пальцев"],
                speak="One, two, three.", demo_en="One, two, three.", demo_ru="Раз, два, три.",
            ),
            _L(
                "Портфель",
                [("bag", "bæɡ", "сумка / портфель"), ("book", "bʊk", "книга"),
                 ("pen", "pen", "ручка"), ("pencil", "ˈpensl", "карандаш"),
                 ("in", "ɪn", "в"), ("on", "ɒn", "на")],
                [("A bag.", "Портфель."), ("A book in a bag.", "Книга в портфеле."),
                 ("A pen on a book.", "Ручка на книге."), ("I have a pencil.", "У меня есть карандаш."),
                 ("Where is the book?", "Где книга?")],
                hello="Школьные вещи нужны, чтобы говорить, где они. Иначе слова висят в воздухе.",
                goal="bag, book, pen, pencil. in — внутри. on — на поверхности.",
                mouth="bag: короткое a как в cat. book: губы чуть вперёд, короткое u, не «бук» как буква.",
                when="Собираешь портфель. Учитель: Where is the book? Ты: In the bag.",
                trap="in и on путают все. Чашка на столе — on. Карандаш в пенале — in. Не «в на».",
                together="A book in a bag. A pen on a book.",
                extra_title="Жест учителя",
                extra_body="Кулак — это сумка (in). Ладонь — стол (on). Клади воображаемую ручку. Назови предлог. "
                           "Тело запоминает быстрее списка.",
                extra_steps=["in = внутри", "on = сверху", "Where is …?"],
                speak="A book in a bag.", demo_en="A book in a bag.", demo_ru="Книга в портфеле.",
            ),
            _L(
                "Числа 6–10",
                [("six", "sɪks", "шесть"), ("seven", "ˈsevn", "семь"),
                 ("eight", "eɪt", "восемь"), ("nine", "naɪn", "девять"),
                 ("ten", "ten", "десять"), ("count", "kaʊnt", "считать")],
                [("Six, seven, eight.", "Шесть, семь, восемь."), ("Nine and ten.", "Девять и десять."),
                 ("I can count.", "Я умею считать."), ("Ten books.", "Десять книг."),
                 ("Count to ten.", "Посчитай до десяти.")],
                hello="Добираем вторую пятёрку. Потом весь ряд 1–10 как песенка, но своими словами, не чужой мелодией.",
                goal="six–ten и фраза I can count.",
                mouth="eight: эйт, не «эйгхт» по буквам. seven: се-вн, второе e почти проглатывается.",
                when="Когда вещей больше пяти. Count to ten — команда дойти до конца.",
                trap="eight пишется странно. Не читай g и h. Только звук [eɪt].",
                together="Six seven eight nine ten. Потом с one.",
                extra_title="Ритм класса",
                extra_body="Хлопок на каждое число. Сбился — начинай с one, не с места ошибки. Так учитель держит хор.",
                extra_steps=["6–10", "1–10", "хлопок"],
                speak="Count to ten.", demo_en="Count to ten.", demo_ru="Посчитай до десяти.",
            ),
            _L(
                "Пенал",
                [("pencil", "ˈpensl", "карандаш"), ("rubber", "ˈrʌbə", "ластик"),
                 ("ruler", "ˈruːlə", "линейка"), ("pen", "pen", "ручка"),
                 ("case", "keɪs", "пенал"), ("have", "hæv", "иметь")],
                [("I have a pencil.", "У меня есть карандаш."), ("I have a rubber.", "У меня есть ластик."),
                 ("A pencil case.", "Пенал."), ("I have a ruler.", "У меня есть линейка."),
                 ("Have you got a pen?", "У тебя есть ручка?")],
                hello="I have — «у меня есть». В русском «есть» в конце, в английском have сразу после I.",
                goal="Школьный набор + I have a …",
                mouth="rubber: ра-бэ, британский ластик. Не «резина» в голове. ruler: ру-лэ, не «рулер».",
                when="Открыл пенал, называешь, что видишь. Учитель спрашивает Have you got a pen?",
                trap="a перед согласным: a pencil, a ruler. Не a apple — это потом с an.",
                together="I have a pencil. I have a rubber. I have a ruler.",
                extra_title="Опрос учителя",
                extra_body="Have you got a pen? Yes, I have. / No. Если нет ручки — скажи I have a pencil. "
                           "Честный ответ важнее красивого.",
                extra_steps=["I have a …", "Yes, I have", "назвать три вещи"],
                speak="I have a pencil.", demo_en="I have a pencil.", demo_ru="У меня есть карандаш.",
            ),
            _L(
                "Где это?",
                [("where", "weə", "где"), ("in", "ɪn", "в"),
                 ("on", "ɒn", "на"), ("under", "ˈʌndə", "под"),
                 ("desk", "desk", "парта"), ("bag", "bæɡ", "сумка")],
                [("Where is the pen?", "Где ручка?"), ("It is on the desk.", "На парте."),
                 ("It is in the bag.", "В сумке."), ("It is under the book.", "Под книгой."),
                 ("Look!", "Смотри!")],
                hello="where — вопрос «где». Учитель прячет вещь глазами, ученик ищет словом, не только пальцем.",
                goal="on / in / under + desk.",
                mouth="where: уэа, не «вхере». under: ан-дэ, d не глотай.",
                when="Вещь пропала. Look! — привлеки взгляд, потом Where is …?",
                trap="under не «андерграунд». Просто «под». The pen is under the book.",
                together="Where is the pen? It is on the desk.",
                extra_title="Три места",
                extra_body="Парта — on. Сумка — in. Книга как крыша — under. Положи ручку в три места и назови. "
                           "Это и есть упражнение класса, только без чужой картинки из книги.",
                extra_steps=["on desk", "in bag", "under book"],
                speak="Where is the pen?", demo_en="Where is the pen?", demo_ru="Где ручка?",
            ),
            _L(
                "Я знаю школу",
                [("one", "wʌn", "один"), ("ten", "ten", "десять"),
                 ("bag", "bæɡ", "сумка"), ("pencil", "ˈpensl", "карандаш"),
                 ("in", "ɪn", "в"), ("on", "ɒn", "на")],
                [("I can count to ten.", "Я считаю до десяти."), ("I have a bag.", "У меня есть сумка."),
                 ("A pencil in a bag.", "Карандаш в сумке."), ("A book on a desk.", "Книга на парте."),
                 ("Where is my pen?", "Где моя ручка?")],
                hello="Собираем модуль: числа, вещи, место. Как контрольная, но с Фокси, без страха.",
                goal="Сказать, что умеешь считать, что есть в портфеле, где лежит книга.",
                mouth="Медленно. Сначала число, потом вещь, потом предлог.",
                when="Перед выходом в школу или к столу с уроками дома.",
                trap="Не пропускай a: I have bag — ломается. I have a bag.",
                together="I have a bag. A book in a bag. I can count to ten.",
                extra_title="Сбор портфеля вслух",
                extra_body="Клади три вещи и называй: I have a … Потом where. Если забыл слово — открой карточку, не молчи.",
                extra_steps=["count", "I have", "in/on"],
                speak="I have a bag.", demo_en="I have a bag.", demo_ru="У меня есть сумка.",
            ),
        ],
    ),
    _unit(
        "room", "Моя комната", "Мебель, игрушки, большой и маленький",
        "Назвать кровать и стол, сказать где игрушка, big/small.",
        "#7fd8c9",
        [
            _L(
                "Кровать и стол",
                [("bed", "bed", "кровать"), ("desk", "desk", "стол / парта"),
                 ("chair", "tʃeə", "стул"), ("lamp", "læmp", "лампа"),
                 ("room", "ruːm", "комната"), ("door", "dɔː", "дверь")],
                [("A bed.", "Кровать."), ("A chair.", "Стул."),
                 ("This is my room.", "Это моя комната."), ("A lamp on a desk.", "Лампа на столе."),
                 ("Open the door.", "Открой дверь.")],
                hello="Комната — набор мест. Учитель обводит глазами: bed, chair, desk, lamp, door.",
                goal="Шесть слов комнаты + This is my room.",
                mouth="chair: ч-эа, не «чайр» с русским Р жёстким. room: долгое у, губы.",
                when="Заходишь в комнату. Можно ткнуть пальцем: This is a bed.",
                trap="desk в школе — парта, дома — письменный стол. Одно слово.",
                together="This is my room. This is a bed. This is a chair.",
                extra_title="Экскурсия",
                extra_body="Пройди глазами по своей комнате и назови три предмета по-английски. Если предмета нет — скажи "
                           "I have a bed anyway: почти у всех есть кровать.",
                extra_steps=["обведи комнату", "три слова", "This is …"],
                speak="This is my room.", demo_en="This is my room.", demo_ru="Это моя комната.",
            ),
            _L(
                "На, в, под",
                [("on", "ɒn", "на"), ("in", "ɪn", "в"),
                 ("under", "ˈʌndə", "под"), ("box", "bɒks", "коробка"),
                 ("bed", "bed", "кровать"), ("chair", "tʃeə", "стул")],
                [("On the chair.", "На стуле."), ("In the box.", "В коробке."),
                 ("Under the bed.", "Под кроватью."), ("The lamp is on the desk.", "Лампа на столе."),
                 ("It is under the chair.", "Под стулом.")],
                hello="Предлоги из школы теперь в комнате. Те же in on under — новые картинки.",
                goal="Закрепить три предлога на мебели.",
                mouth="the — короткое «зе» перед согласным. Не пропускай: on the chair.",
                when="Ищешь носок, машинку, книгу. Классика: under the bed.",
                trap="Не говори «на стул» русским порядком. Английский: on the chair — предлог первым после is.",
                together="On the chair. In the box. Under the bed.",
                extra_title="Прятки",
                extra_body="Спрячь карандаш. Скажи, где он, только по-английски. Фокси проверяет предлог, не идеальный акцент.",
                extra_steps=["спрячь", "on/in/under", "полная фраза"],
                speak="Under the bed.", demo_en="Under the bed.", demo_ru="Под кроватью.",
            ),
            _L(
                "Игрушки",
                [("ball", "bɔːl", "мяч"), ("doll", "dɒl", "кукла"),
                 ("car", "kɑː", "машина"), ("train", "treɪn", "поезд"),
                 ("toy", "tɔɪ", "игрушка"), ("box", "bɒks", "коробка")],
                [("A ball.", "Мяч."), ("A toy car.", "Игрушечная машина."),
                 ("I have a doll.", "У меня есть кукла."), ("A train in a box.", "Поезд в коробке."),
                 ("Let's play.", "Давай играть.")],
                hello="Игрушка — toy. Конкретные: ball, doll, car, train. Let's play — зовём играть.",
                goal="Назвать игрушки и пригласить: Let's play.",
                mouth="Let's: летс, слитно. play: плэй. toy: той, губы.",
                when="Достаёшь ящик. Let's play — начало, не конец урока.",
                trap="doll не «долл» как доллар. Короткое o. car — долгая а, не «кар» с русским Р раскатом, но понятно и так.",
                together="Let's play. I have a ball. I have a car.",
                extra_title="Приглашение",
                extra_body="Let's = let us, «давай мы». Это учительский старт игры. Ответь Yes! или Wait! (подожди) — wait уже будет позже, сегодня Yes.",
                extra_steps=["Let's play", "назвать игрушку", "I have a …"],
                speak="Let's play.", demo_en="Let's play.", demo_ru="Давай играть.",
            ),
            _L(
                "Большой и маленький",
                [("big", "bɪɡ", "большой"), ("small", "smɔːl", "маленький"),
                 ("ball", "bɔːl", "мяч"), ("box", "bɒks", "коробка"),
                 ("car", "kɑː", "машина"), ("bed", "bed", "кровать")],
                [("A big bed.", "Большая кровать."), ("A small car.", "Маленькая машина."),
                 ("It is big.", "Это большое."), ("It is small.", "Это маленькое."),
                 ("A big box.", "Большая коробка.")],
                hello="Описание — следующий шаг после имени вещи. Учитель всегда добавляет размер.",
                goal="Прилагательное перед словом: a big bed, a small car.",
                mouth="small: смол, l в конце держи. big: биг, g не превращай в к.",
                when="Две машины, два мяча. Сравни. It is big / It is small.",
                trap="По-русски «мяч большой» после слова. По-английски big раньше: a big ball.",
                together="A big bed. A small car. It is small.",
                extra_title="Порядок слов",
                extra_body="a + размер + вещь. Без a фраза звучит как заголовок. С a — как речь учителя, указывающего на предмет.",
                extra_steps=["a", "big/small", "вещь"],
                speak="A big bed.", demo_en="A big bed.", demo_ru="Большая кровать.",
            ),
            _L(
                "Моя комната",
                [("room", "ruːm", "комната"), ("bed", "bed", "кровать"),
                 ("lamp", "læmp", "лампа"), ("toy", "tɔɪ", "игрушка"),
                 ("on", "ɒn", "на"), ("in", "ɪn", "в")],
                [("This is my room.", "Это моя комната."), ("My bed is big.", "Моя кровать большая."),
                 ("A lamp on my desk.", "Лампа на столе."), ("Toys in a box.", "Игрушки в коробке."),
                 ("I like my room.", "Мне нравится моя комната.")],
                hello="Сводим мебель + предлоги + like. Короткий рассказ, не список.",
                goal="3–4 фразы подряд про свою комнату.",
                mouth="Связывай паузой, не «и-и-и» по-русски. Точка — вдох.",
                when="Гостям или Фокси по видеосвязи. Это и есть speaking.",
                trap="my room не the my room. my уже определяет.",
                together="This is my room. I like my room. Toys in a box.",
                extra_title="Рассказ из четырёх фраз",
                extra_body="1 This is my room. 2 A big bed. 3 A lamp on the desk. 4 I like my room. "
                           "Учитель слушает цепочку, не каждое слово по отдельности.",
                extra_steps=["вход", "кровать", "лампа", "like"],
                speak="I like my room.", demo_en="I like my room.", demo_ru="Мне нравится моя комната.",
            ),
            _L(
                "Я знаю комнату",
                [("bed", "bed", "кровать"), ("chair", "tʃeə", "стул"),
                 ("ball", "bɔːl", "мяч"), ("big", "bɪɡ", "большой"),
                 ("small", "smɔːl", "маленький"), ("under", "ˈʌndə", "под")],
                [("A ball under the bed.", "Мяч под кроватью."), ("A small doll.", "Маленькая кукла."),
                 ("Sit on the chair.", "Сядь на стул."), ("A big box.", "Большая коробка."),
                 ("This is my room.", "Это моя комната.")],
                hello="Проверка модуля комнаты. Я прячу мяч словами — ты находишь смыслом.",
                goal="Предлог + размер + мебель в одной голове.",
                mouth="Sit on the chair — команда. sit уже знакомо по звукам позже, сейчас как целое слово.",
                when="Уборка: мяч under, кукла in the box, сядь on the chair.",
                trap="Sit on, не sit in the chair (если это обычный стул, не кресло-мешок).",
                together="Sit on the chair. A ball under the bed.",
                extra_title="Команды учителя",
                extra_body="Sit. Look. Open the door. Let's play. В классе так живут. Повтори команды телом, потом ртом.",
                extra_steps=["Sit", "Look", "Let's play"],
                speak="Sit on the chair.", demo_en="Sit on the chair.", demo_ru="Сядь на стул.",
            ),
        ],
    ),
    _unit(
        "pets", "Мои питомцы", "Кот, собака, птица, рыбка — у меня есть",
        "Назвать животных, сказать I have a …, большой/маленький питомец.",
        "#f5ed75",
        [
            _L(
                "Кот и собака",
                [("cat", "kæt", "кот"), ("dog", "dɒɡ", "собака"),
                 ("bird", "bɜːd", "птица"), ("fish", "fɪʃ", "рыба"),
                 ("pet", "pet", "питомец"), ("fox", "fɒks", "лиса")],
                [("A cat.", "Кот."), ("A dog.", "Собака."),
                 ("A bird and a fish.", "Птица и рыба."), ("This is a pet.", "Это питомец."),
                 ("Foxy is a fox.", "Фокси — лиса.")],
                hello="Кто живёт дома с тобой? Сегодня называем его фразой This is a … Foxy — лиса, обычно не домашний зверь: это шутка учителя.",
                goal="cat dog bird fish pet. This is a …",
                mouth="bird: бёд, r не раскатывай. fish: ш в конце, не «фис».",
                when="В зоомагазине, на картинке, у окна если голубь — bird.",
                trap="a cat, не a catа. fish в детской речи часто и про одну рыбку.",
                together="This is a cat. This is a dog. This is a pet.",
                extra_title="Кто не pet",
                extra_body="Foxy is a fox. Fox не типичный pet. Можно сказать Foxy is my friend. friend — друг, слово на потом, "
                           "сегодня достаточно Foxy is a fox.",
                extra_steps=["This is a …", "pet или нет", "Foxy is a fox"],
                speak="This is a cat.", demo_en="This is a cat.", demo_ru="Это кот.",
            ),
            _L(
                "У меня есть",
                [("have", "hæv", "иметь"), ("cat", "kæt", "кот"),
                 ("dog", "dɒɡ", "собака"), ("fish", "fɪʃ", "рыба"),
                 ("bird", "bɜːd", "птица"), ("pet", "pet", "питомец")],
                [("I have a cat.", "У меня есть кот."), ("I have a dog.", "У меня есть собака."),
                 ("I have a fish.", "У меня есть рыбка."), ("I have a pet.", "У меня есть питомец."),
                 ("I do not have a dog.", "У меня нет собаки.")],
                hello="Честно: если питомца нет, говори I do not have. Учитель любит правду больше красивой лжи.",
                goal="I have a … / I do not have a …",
                mouth="do not можно don't позже. Сегодня полностью: I do not have a dog.",
                when="Знакомишься: про семью уже сказали, теперь про животных.",
                trap="I have cat без a — ошибка. I have a cat.",
                together="I have a cat. I do not have a dog. Выбери правду про себя.",
                extra_title="Правда класса",
                extra_body="Учитель спрашивает по кругу. Не копируй соседа. Английский для своей жизни, не для хора вранья.",
                extra_steps=["есть", "нет", "a + животное"],
                speak="I have a cat.", demo_en="I have a cat.", demo_ru="У меня есть кот.",
            ),
            _L(
                "Это не …",
                [("cat", "kæt", "кот"), ("dog", "dɒɡ", "собака"),
                 ("bird", "bɜːd", "птица"), ("fish", "fɪʃ", "рыба"),
                 ("yes", "jes", "да"), ("no", "nəʊ", "нет")],
                [("It is a cat.", "Это кот."), ("It is not a dog.", "Это не собака."),
                 ("Is it a bird?", "Это птица?"), ("Yes, it is.", "Да."),
                 ("No, it is not.", "Нет.")],
                hello="Учитель показывает картинку и ловит: Is it a dog? Ты учишься не только называть, но и отвергать.",
                goal="It is / It is not. Yes, it is. No, it is not.",
                mouth="Is it …? Голос вверх в конце — это вопрос. В русском тоже, но здесь обязательно is в начале.",
                when="Угадайка. Не стыдно ошибиться: No, it is a cat.",
                trap="It is not a dog. Не It no dog. not стоит после is.",
                together="Is it a cat? Yes, it is. Is it a dog? No, it is not.",
                extra_title="Вопрос с is",
                extra_body="Порядок: Is + it + a + слово. Ответ короткий: Yes, it is. Длинный: Yes, it is a cat. "
                           "Сначала короткий, как в классе у доски.",
                extra_steps=["Is it …?", "Yes, it is", "No, it is not"],
                speak="Is it a cat?", demo_en="Is it a cat?", demo_ru="Это кот?",
            ),
            _L(
                "Большой пёс",
                [("big", "bɪɡ", "большой"), ("small", "smɔːl", "маленький"),
                 ("dog", "dɒɡ", "собака"), ("cat", "kæt", "кот"),
                 ("bird", "bɜːd", "птица"), ("fish", "fɪʃ", "рыба")],
                [("A big dog.", "Большая собака."), ("A small cat.", "Маленький кот."),
                 ("A small bird.", "Маленькая птица."), ("A big fish.", "Большая рыба."),
                 ("My pet is small.", "Мой питомец маленький.")],
                hello="Размер снова, теперь на животных. Учитель сравнивает двух.",
                goal="a big dog, a small cat, My pet is …",
                mouth="My pet is small. is снова связка. Не My pet small.",
                when="На улице большая собака — a big dog. На руках котёнок — a small cat.",
                trap="fish может быть big в море и small в банке. Слово то же.",
                together="A big dog. A small cat. My pet is small.",
                extra_title="Сравнение",
                extra_body="Укажи два: This dog is big. This cat is small. this уже было в семье. Повторяем в новой теме — так закрепляют в живом уроке.",
                extra_steps=["big dog", "small cat", "My pet is …"],
                speak="A big dog.", demo_en="A big dog.", demo_ru="Большая собака.",
            ),
            _L(
                "Я вижу",
                [("see", "siː", "видеть"), ("look", "lʊk", "смотреть"),
                 ("cat", "kæt", "кот"), ("bird", "bɜːd", "птица"),
                 ("dog", "dɒɡ", "собака"), ("can", "kæn", "мочь")],
                [("I see a cat.", "Я вижу кота."), ("Look! A bird.", "Смотри! Птица."),
                 ("I can see a dog.", "Я могу видеть собаку."), ("Look at the fish.", "Посмотри на рыбку."),
                 ("Can you see it?", "Видишь?")],
                hello="see — видишь глазами. look — направляешь взгляд. Учитель: Look! потом I see …",
                goal="Look! I see a … Can you see it?",
                mouth="Look at the fish. at маленький. Не Look the fish.",
                when="Окно, улица, картинка. Look! — внимание класса.",
                trap="see не sea (море). Одинаково почти звучат — смысл разный. Сегодня только see «видеть».",
                together="Look! I see a cat. Can you see it?",
                extra_title="Два глагола",
                extra_body="Look — команда. see — результат. Сначала Look, потом I see. Как в классе у окна.",
                extra_steps=["Look!", "I see a …", "Can you see it?"],
                speak="I see a cat.", demo_en="I see a cat.", demo_ru="Я вижу кота.",
            ),
            _L(
                "Я знаю питомцев",
                [("cat", "kæt", "кот"), ("dog", "dɒɡ", "собака"),
                 ("have", "hæv", "иметь"), ("see", "siː", "видеть"),
                 ("big", "bɪɡ", "большой"), ("pet", "pet", "питомец")],
                [("I have a pet.", "У меня есть питомец."), ("I see a dog.", "Я вижу собаку."),
                 ("It is not a cat.", "Это не кот."), ("A big dog.", "Большая собака."),
                 ("Look at the cat.", "Посмотри на кота.")],
                hello="Сборка модуля животных. Говори правду про своего или про Фокси.",
                goal="have + see + not + размер.",
                mouth="Четыре фразы, четыре вдоха.",
                when="Можно у клетки, у окна, у мягкой игрушки.",
                trap="Не мешай I have и I see: одно — твоё, другое — в поле зрения сейчас.",
                together="I have a pet. I see a cat. It is not a dog.",
                extra_title="Карточка «мой питомец»",
                extra_body="Назови: кто, большой/маленький, I have / I do not have. Это портфолио, только устное, без чужого шаблона книги.",
                extra_steps=["кто", "размер", "есть/нет"],
                speak="I have a pet.", demo_en="I have a pet.", demo_ru="У меня есть питомец.",
            ),
        ],
    ),
    _unit(
        "food", "Моя еда", "Еда, нравится / не нравится, пожалуйста",
        "Назвать еду, сказать I like, попросить politely.",
        "#3a2953",
        [
            _L(
                "Яблоко и молоко",
                [("apple", "ˈæpl", "яблоко"), ("banana", "bəˈnɑːnə", "банан"),
                 ("milk", "mɪlk", "молоко"), ("cake", "keɪk", "торт / пирожное"),
                 ("bread", "bred", "хлеб"), ("egg", "eɡ", "яйцо")],
                [("An apple.", "Яблоко."), ("A banana.", "Банан."),
                 ("Milk, please.", "Молоко, пожалуйста."), ("I eat bread.", "Я ем хлеб."),
                 ("An egg.", "Яйцо.")],
                hello="Еда — лучший урок: можно показать на кухне. an apple, an egg — an перед гласным звуком.",
                goal="Продукты + an/a. please в конце просьбы.",
                mouth="apple: эпл, не «эппле». banana: ударение на на. cake: кейк, не «каке».",
                when="Завтрак. Milk, please. — просишь, не командуешь.",
                trap="an apple не a apple. Ухо: слово начинается на гласный звук.",
                together="An apple. A banana. Milk, please.",
                extra_title="a и an",
                extra_body="a banana, a cake, a dog. an apple, an egg. Это не «правило для тетради», это удобство произношения, учитель так и объясняет.",
                extra_steps=["a + согласный", "an + гласный", "please"],
                speak="An apple.", demo_en="An apple.", demo_ru="Яблоко.",
            ),
            _L(
                "Нравится",
                [("like", "laɪk", "нравиться"), ("apple", "ˈæpl", "яблоко"),
                 ("cake", "keɪk", "торт"), ("milk", "mɪlk", "молоко"),
                 ("banana", "bəˈnɑːnə", "банан"), ("yum", "jʌm", "ням")],
                [("I like cake.", "Люблю торт."), ("I like milk.", "Люблю молоко."),
                 ("I do not like banana.", "Не люблю банан."), ("Yum, yum!", "Ням!"),
                 ("I like apples.", "Люблю яблоки.")],
                hello="like — вкус и выбор. Учитель не спорит, если не любишь лук. Сегодня банан можно не любить.",
                goal="I like / I do not like + еда.",
                mouth="like: лайк. do not like — ровно, без драмы, просто факт.",
                when="Меню, холодильник, праздник. Yum — радость, не грамматика.",
                trap="I like apple иногда говорят дети. Лучше I like apples или I like cake без s как вещество/блюдо.",
                together="I like cake. I do not like … — вставь своё.",
                extra_title="Вежливый отказ",
                extra_body="No, thank you. появится в следующем уроке. Сегодня достаточно I do not like. Честно и спокойно, как учит хороший педагог.",
                extra_steps=["I like", "I do not like", "Yum"],
                speak="I like cake.", demo_en="I like cake.", demo_ru="Люблю торт.",
            ),
            _L(
                "Я голодный",
                [("hungry", "ˈhʌŋɡri", "голодный"), ("thirsty", "ˈθɜːsti", "хочет пить"),
                 ("eat", "iːt", "есть"), ("drink", "drɪŋk", "пить"),
                 ("please", "pliːz", "пожалуйста"), ("yum", "jʌm", "ням")],
                [("I am hungry.", "Я голоден."), ("I am thirsty.", "Хочу пить."),
                 ("I eat.", "Я ем."), ("I drink milk.", "Я пью молоко."),
                 ("Eat, please.", "Ешь, пожалуйста.")],
                hello="I am снова: I am hungry, I am thirsty. Тело просит — язык называет.",
                goal="hungry/thirsty + eat/drink.",
                mouth="thirsty: th в начале, язык к зубам. hungry: хан-гри, ng как в пении.",
                when="Перед едой, после улицы. Учитель: Are you hungry?",
                trap="hungry не angry (злой). Похожи для русского уха. Голод — hungry.",
                together="I am hungry. I eat. I am thirsty. I drink milk.",
                extra_title="Пара тела",
                extra_body="Голод → eat. Жажда → drink. Не пей, когда хочешь есть, в языке тоже разные глаголы. Учитель разделяет, чтобы не было каши.",
                extra_steps=["I am hungry", "eat", "I am thirsty", "drink"],
                speak="I am hungry.", demo_en="I am hungry.", demo_ru="Я голоден.",
            ),
            _L(
                "Пожалуйста и спасибо",
                [("please", "pliːz", "пожалуйста"), ("thanks", "θæŋks", "спасибо"),
                 ("thank", "θæŋk", "благодарить"), ("you", "juː", "тебе"),
                 ("yes", "jes", "да"), ("no", "nəʊ", "нет")],
                [("Please.", "Пожалуйста (просьба)."), ("Thank you.", "Спасибо."),
                 ("Yes, please.", "Да, пожалуйста."), ("No, thank you.", "Нет, спасибо."),
                 ("Milk, please.", "Молоко, пожалуйста.")],
                hello="Вежливость — отдельный урок, не сноска. Так учитель в 1 классе и делает: сначала слова еды, потом манеры стола.",
                goal="please / Thank you / Yes, please / No, thank you.",
                mouth="Thank: th, не «сэнк». you короткое. Together: Thank you.",
                when="Дают угощение. Берут. Отказываются. Четыре ситуации — четыре фразы.",
                trap="please в конце просьбы: Cake, please. Не Please cake как приказ.",
                together="Cake, please. Thank you. No, thank you.",
                extra_title="Два please",
                extra_body="Русское «пожалуйста» и когда просишь, и когда «не за что». Английский делит: просьба — please, после подарка — Thank you. "
                           "You're welcome позже. Сегодня хватит Thank you.",
                extra_steps=["просьба + please", "Thank you", "No, thank you"],
                speak="Thank you.", demo_en="Thank you.", demo_ru="Спасибо.",
            ),
            _L(
                "Ем и пью",
                [("eat", "iːt", "есть"), ("drink", "drɪŋk", "пить"),
                 ("apple", "ˈæpl", "яблоко"), ("milk", "mɪlk", "молоко"),
                 ("egg", "eɡ", "яйцо"), ("bread", "bred", "хлеб")],
                [("I eat an apple.", "Я ем яблоко."), ("I drink milk.", "Я пью молоко."),
                 ("I eat bread.", "Я ем хлеб."), ("I eat an egg.", "Я ем яйцо."),
                 ("I like bread.", "Люблю хлеб.")],
                hello="Кладём еду на глагол. I eat + еда. I drink + напиток. Молоко пьют, яблоко едят — учитель это проговаривает.",
                goal="Соединить eat/drink с продуктами и a/an.",
                mouth="I eat an apple — an между eat и apple удобно языку.",
                when="За столом. Комментарий к действию, как учит малышей: делаешь — говоришь.",
                trap="I drink an apple — нельзя. Яблоко не drink.",
                together="I eat an apple. I drink milk. I eat bread.",
                extra_title="Правило кухни",
                extra_body="Жидкость — drink. Кусок — eat. Суп позже. Сегодня молоко vs яблоко/хлеб/яйцо/торт.",
                extra_steps=["eat + еда", "drink + молоко", "an apple"],
                speak="I eat an apple.", demo_en="I eat an apple.", demo_ru="Я ем яблоко.",
            ),
            _L(
                "Я знаю еду",
                [("apple", "ˈæpl", "яблоко"), ("like", "laɪk", "нравиться"),
                 ("hungry", "ˈhʌŋɡri", "голодный"), ("please", "pliːz", "пожалуйста"),
                 ("thanks", "θæŋks", "спасибо"), ("milk", "mɪlk", "молоко")],
                [("I am hungry.", "Я голоден."), ("I like apples.", "Люблю яблоки."),
                 ("Milk, please.", "Молоко, пожалуйста."), ("Thank you.", "Спасибо."),
                 ("No, thank you.", "Нет, спасибо.")],
                hello="Сцена за столом целиком. Это и есть «все задания модуля», только наши, живые.",
                goal="Голод → выбор → просьба → спасибо или отказ.",
                mouth="Не тараторь вежливость. Пауза после please.",
                when="Любая еда дома сегодня.",
                trap="Смешать Yes, please и No, thank you. Одно из двух.",
                together="I am hungry. Cake, please. Thank you.",
                extra_title="Мини-обед",
                extra_body="1 I am hungry. 2 I like … 3 …, please. 4 Thank you. Если не хочешь: No, thank you. Учитель ставит звёзды за цепочку.",
                extra_steps=["голод", "like", "please", "thanks"],
                speak="Milk, please.", demo_en="Milk, please.", demo_ru="Молоко, пожалуйста.",
            ),
        ],
    ),
    _unit(
        "play", "Время играть", "Игры, движение, повторяем весь год",
        "Let's play, бегать и прыгать, собрать слова всех модулей.",
        "#ee7349",
        [
            _L(
                "Давай играть",
                [("play", "pleɪ", "играть"), ("game", "ɡeɪm", "игра"),
                 ("fun", "fʌn", "весело"), ("friend", "frend", "друг"),
                 ("let", "let", "давай / пусть"), ("yes", "jes", "да")],
                [("Let's play.", "Давай играть."), ("Let's play a game.", "Давай сыграем."),
                 ("It is fun.", "Это весело."), ("You are my friend.", "Ты мой друг."),
                 ("Yes, let's play.", "Да, давай играть.")],
                hello="Игра — не награда после урока, это часть урока. Let's play уже было, сегодня разбираем по косточкам.",
                goal="Let's play a game. friend. fun.",
                mouth="friend: френд, i не «ай». fun: фан, как в sun.",
                when="Перемена, двор, комната. You are my friend — Фокси про тебя.",
                trap="game не play. play — глагол, game — партия/игра как вещь.",
                together="Let's play a game. It is fun. You are my friend.",
                extra_title="Let's ещё раз",
                extra_body="Let's + глагол: Let's play, Let's eat, Let's count. Шаблон учителя на все модули. Сегодня осознаём шаблон.",
                extra_steps=["Let's + play", "a game", "friend"],
                speak="Let's play a game.", demo_en="Let's play a game.", demo_ru="Давай сыграем.",
            ),
            _L(
                "Беги и прыгай",
                [("run", "rʌn", "бежать"), ("jump", "dʒʌmp", "прыгать"),
                 ("sit", "sɪt", "сидеть"), ("stop", "stɒp", "стоп"),
                 ("go", "ɡəʊ", "идти / начать"), ("play", "pleɪ", "играть")],
                [("Run!", "Беги!"), ("Jump!", "Прыгай!"),
                 ("Sit down.", "Сядь."), ("Stop!", "Стоп!"),
                 ("Go!", "Начали!")],
                hello="Команды тела. Учитель физминутки: Run! Stop! Sit down! Ты делаешь, потом говоришь.",
                goal="Повелительное наклонение: голое слово-крик без please (это игра, не стол).",
                mouth="Jump: дж в начале. Stop: p в конце, губы сомкни.",
                when="Двор, зал, минутка на уроке. Go! — старт. Stop! — замри.",
                trap="Sit down — down добавляет «на место». Sit одно тоже можно.",
                together="Go! Run! Jump! Stop! Sit down.",
                extra_title="Саймон говорит, по-нашему",
                extra_body="Foxy говорит команду — ты выполняешь только если было слово Foxy says. "
                           "Это наша игра, не чужая книга. Слушать важнее бежать.",
                extra_steps=["слушай", "делай", "скажи команду сам"],
                speak="Jump!", demo_en="Jump!", demo_ru="Прыгай!",
            ),
            _L(
                "Семья и школа снова",
                [("mum", "mʌm", "мама"), ("hello", "həˈləʊ", "привет"),
                 ("bag", "bæɡ", "сумка"), ("ten", "ten", "десять"),
                 ("happy", "ˈhæpi", "радостный"), ("pencil", "ˈpensl", "карандаш")],
                [("Hello, mum!", "Привет, мама!"), ("I have a bag.", "У меня есть сумка."),
                 ("I can count to ten.", "Считаю до десяти."), ("I am happy.", "Я рад."),
                 ("I have a pencil.", "У меня есть карандаш.")],
                hello="Повтор — не стыдно. Учитель возвращает старое, когда новое уже есть, иначе слова умирают.",
                goal="Прогнать модули 1–2 вперемешку.",
                mouth="Чистота важнее скорости.",
                when="Любое утро.",
                trap="Не переходи на русский в середине фразы. Договори до точки.",
                together="Hello, mum! I have a bag. I can count to ten.",
                extra_title="День на английском с утра",
                extra_body="Три фразы до школы: привет маме, портфель, настроение. Это домашняя привычка, которую даёт живой учитель.",
                extra_steps=["семья", "школа", "чувство"],
                speak="Hello, mum!", demo_en="Hello, mum!", demo_ru="Привет, мама!",
            ),
            _L(
                "Комната и питомцы снова",
                [("bed", "bed", "кровать"), ("cat", "kæt", "кот"),
                 ("under", "ˈʌndə", "под"), ("dog", "dɒɡ", "собака"),
                 ("big", "bɪɡ", "большой"), ("ball", "bɔːl", "мяч")],
                [("A cat on the bed.", "Кот на кровати."), ("A ball under the bed.", "Мяч под кроватью."),
                 ("I have a dog.", "У меня есть собака."), ("A big dog.", "Большая собака."),
                 ("This is my room.", "Это моя комната.")],
                hello="Смешиваем комнату и животных: кот любит кровать, мяч любит пол.",
                goal="Предлоги + pet + размер.",
                mouth="on the bed / under the bed — одна мебель, два мира.",
                when="Уборка и питомец в кадре.",
                trap="cat on bed без the — беднее. the bed — конкретная кровать.",
                together="A cat on the bed. A ball under the bed.",
                extra_title="Одна картинка — две фразы",
                extra_body="Учитель держит одну сцену и выжимает язык: кто, где, какой. Не десять картинок — одна глубокая.",
                extra_steps=["кто", "где", "размер"],
                speak="A cat on the bed.", demo_en="A cat on the bed.", demo_ru="Кот на кровати.",
            ),
            _L(
                "Еда и игра снова",
                [("cake", "keɪk", "торт"), ("play", "pleɪ", "играть"),
                 ("please", "pliːz", "пожалуйста"), ("jump", "dʒʌmp", "прыгать"),
                 ("like", "laɪk", "нравиться"), ("run", "rʌn", "бежать")],
                [("Cake, please.", "Торт, пожалуйста."), ("I like cake.", "Люблю торт."),
                 ("Let's play.", "Давай играть."), ("Run and jump.", "Беги и прыгай."),
                 ("Thank you.", "Спасибо.")],
                hello="Праздник: торт и игра. Вежливость не выключаем, даже если прыгаем.",
                goal="please + like + let's + команды.",
                mouth="После торта Thank you, потом Let's play. Порядок как у воспитанного класса.",
                when="День рождения, воскресенье, пятница.",
                trap="Не кричи Cake! без please. Игра не отменяет манеры.",
                together="Cake, please. Thank you. Let's play. Jump!",
                extra_title="Праздник по ролям",
                extra_body="Ты гость: please и thank you. Ты ведущий: Let's play, Jump, Stop. Учитель меняет роли — так учат диалог, не зубрёжку.",
                extra_steps=["гость", "спасибо", "ведущий"],
                speak="Let's play.", demo_en="Let's play.", demo_ru="Давай играть.",
            ),
            _L(
                "Я ученик Foxy",
                [("hello", "həˈləʊ", "привет"), ("name", "neɪm", "имя"),
                 ("family", "ˈfæmɪli", "семья"), ("school", "skuːl", "школа"),
                 ("friend", "frend", "друг"), ("foxy", "ˈfɒksi", "Foxy")],
                [("Hello! I am a kid.", "Привет! Я ребёнок."), ("This is my family.", "Это моя семья."),
                 ("I like school.", "Мне нравится школа."), ("You are my friend.", "Ты мой друг."),
                 ("I am with Foxy.", "Я с Foxy.")],
                hello="Выпускной 1 класса устной линии. Дальше научим читать по звукам. Сегодня — речь.",
                goal="Собрать визитку: кто ты, семья, школа, друг Фокси.",
                mouth="Медленная речь на сцене. Каждая фраза — поклон.",
                when="Покажи маме. Это отчёт, не тест.",
                trap="Не читай по слогам как робот. Говори как человеку.",
                together="Hello! This is my family. You are my friend, Foxy.",
                extra_title="Что дальше",
                extra_body="Ты умеешь здороваться, считать, просить еду, звать играть. Следующие уроки — звуки: как читать cat самим. "
                           "Я останусь учителем. Сначала рот, потом буквы. Так и надо.",
                extra_steps=["визитка", "похвала себе", "готовы к чтению"],
                speak="You are my friend.", demo_en="You are my friend.", demo_ru="Ты мой друг.",
            ),
        ],
    ),
]
