"""Детские картинки слов: эмодзи Twemoji + свои пиктограммы. Не NASA-солнце."""
from pathlib import Path

# hex без fe0f — файлы Twemoji 14
EMOJI: dict[str, str] = {
    "sun": "1f31e",  # солнышко с лицом
    "cat": "1f431",
    "dog": "1f436",
    "hat": "1f9e2",
    "bag": "1f45c",
    "bus": "1f68c",
    "bed": "1f6cf",
    "cup": "2615",
    "red": "1f534",
    "duck": "1f986",
    "pig": "1f437",
    "fox": "1f98a",
    "box": "1f4e6",
    "tree": "1f333",
    "moon": "1f31b",
    "car": "1f697",
    "star": "2b50",
    "book": "1f4d6",
    "rain": "1f327",
    "bee": "1f41d",
    "boat": "26f5",
    "coat": "1f9e5",
    "cow": "1f42e",
    "owl": "1f989",
    "chair": "1fa91",
    "ear": "1f442",
    "hair": "1f487",
    "ring": "1f48d",
    "king": "1f451",
    "ship": "1f6a2",
    "fish": "1f41f",
    "jam": "1f36f",
    "van": "1f690",
    "web": "1f578",
    "pin": "1f4cc",
    "map": "1f5fa",
    "pan": "1f373",
    "mat": "1f9f9",
    "tap": "1f6b0",
    "cap": "1f9e2",
    "ten": "1f51f",
    "hen": "1f414",
    "sock": "1f9e6",
    "hill": "26f0",
    "bell": "1f514",
    "doll": "1f9f8",
    "zip": "1f456",
    "zoo": "1f981",
    "queen": "1f478",
    "night": "1f303",
    "light": "1f4a1",
    "food": "1f35e",
    "spoon": "1f944",
    "fork": "1f374",
    "park": "1f3de",
    "farm": "1f69c",
    "coin": "1fa99",
    "oil": "1fad2",
    "air": "1f4a8",
    "stairs": "1fa9c",
    "train": "1f686",
    "tail": "1f43e",
    "pen": "1f58a",
    "pot": "1f372",
    "mug": "1f3ba",
    "mum": "1f469",
    "dad": "1f468",
    "man": "1f9d4",
    "kid": "1f9d2",
    "kit": "1f9f0",
    "milk": "1f95b",
    "net": "1f3d3",
    "nap": "1f634",
    "sit": "1f9cd",
    "sad": "1f622",
    "run": "1f3c3",
    "look": "1f440",
    "see": "1f440",
    "sleep": "1f634",
    "sing": "1f3a4",
    "song": "1f3b5",
    "jump": "1f938",
    "kick": "26bd",
    "hit": "1f94a",
    "hop": "1f9b6",
    "dig": "1faa8",
    "cut": "2702",
    "cook": "1f9d1-200d-1f373",
    "wait": "23f3",
    "hear": "1f442",
    "yes": "2705",
    "yum": "1f60b",
    "hello": "1f44b",
    "hi": "1f44b",
    "name": "1f3f7",
    "foxi": "1f98a",
    "you": "1f449",
    "sister": "1f467",
    "brother": "1f466",
    "baby": "1f476",
    "family": "1f46a",
    "happy": "1f60a",
    "smile": "1f604",
    "cry": "1f622",
    "bad": "1f44e",
    "blue": "1f535",
    "yellow": "1f7e1",
    "black": "26ab",
    "white": "26aa",
    "one": "31-20e3",
    "two": "32-20e3",
    "three": "33-20e3",
    "four": "34-20e3",
    "five": "35-20e3",
    "seven": "37-20e3",
    "eight": "38-20e3",
    "nine": "39-20e3",
    "number": "1f522",
    "count": "1f522",
    "pencil": "270f",
    "rubber": "1f9f9",
    "ruler": "1f4cf",
    "case": "1f4e6",
    "have": "1f44b",
    "where": "1f50d",
    "under": "2b07",
    "desk": "1fa91",
    "lamp": "1f4a1",
    "door": "1f6aa",
    "ball": "26bd",
    "toy": "1f9f8",
    "small": "1f90f",
    "bird": "1f426",
    "pet": "1f43e",
    "hungry": "1f37d",
    "thirsty": "1f4a7",
    "eat": "1f37d",
    "drink": "1f964",
    "please": "1f64f",
    "thanks": "1f64f",
    "thank": "1f64f",
    "apple": "1f34e",
    "banana": "1f34c",
    "cake": "1f370",
    "bread": "1f35e",
    "egg": "1f95a",
    "game": "1f3ae",
    "friend": "1f91d",
    "let": "1f91d",
    "stop": "1f6d1",
    "go": "1f3c3",
    "school": "1f3eb",
    "wow": "1f62e",
    "now": "1f550",
    "how": "2753",
    "up": "2b06",
    "down": "2b07",
    "on": "1f51b",
    "off": "1f6d1",
    "and": "2795",
    "it": "1f449",
    "if": "1f914",
    "hot": "1f525",
    "wet": "1f4a6",
    "big": "1f4d0",
    "long": "1f4cf",
    "good": "1f44d",
    "green": "1f7e2",
    "thick": "1f955",
    "thin": "1f9be",
    "this": "1f448",
    "that": "1f449",
    "six": "36-20e3",
    "foot": "1f9b6",
    "feet": "1f9b6",
    "arm": "1f4aa",
    "leg": "1f9b5",
    "lip": "1f444",
    "chin": "1f9b5",
    "neck": "1f9b5",
    "rib": "1f9b4",
    "path": "1f6e4",
    "road": "1f6e3",
    "room": "1f6aa",
    "town": "1f3d8",
    "wood": "1fab5",
    "log": "1fab5",
    "sand": "1f3d6",
    "soil": "1fab1",
    "fog": "1f32b",
    "fan": "1faad",
    "rug": "1f9f1",
    "lid": "1f373",
    "tin": "1f6e2",
    "can": "1f96b",
    "jar": "1f9c3",
    "jug": "1f964",
    "boot": "1f97e",
    "vest": "1f455",
    "wig": "1f9b4",
    "quilt": "1f9f8",
    "chip": "1f35f",
    "dish": "1f37d",
    "soap": "1f9e6",
    "loaf": "1f35e",
    "corn": "1f33d",
    "toad": "1f438",
    "rat": "1f400",
    "moth": "1f98b",
    "yak": "1f9ac",
    "jet": "1f6e9",
    "quiz": "1f4dd",
    "queen": "1f478",
    "cash": "1f4b5",
    "shop": "1f3ea",
    "shed": "1f3e0",
    "sail": "26f5",
    "pair": "1f45e",
    "fair": "1f3a1",
    "year": "1f4c5",
    "dear": "1f496",
    "tear": "1f622",
    "burn": "1f525",
    "turn": "1f504",
    "fur": "1f43b",
    "sport": "1f3c0",
    "point": "1f446",
    "join": "1f91d",
    "boil": "1f375",
    "pain": "1f915",
    "high": "1f4c8",
    "right": "2705",
    "fight": "1f94a",
    "sight": "1f441",
    "hang": "1f3d3",
    "much": "1f4af",
    "less": "1f4a3",
    "mess": "1f9f9",
    "pass": "1f3ab",
    "kiss": "1f48b",
    "hiss": "1f40d",
    "boss": "1f454",
    "fill": "1f4a7",
    "pull": "1f9f6",
    "well": "1f4a7",
    "bell": "1f514",
    "top": "1f3d3",
    "pit": "1f573",
    "tip": "1f4a1",
    "sap": "1f33f",
    "sat": "1f9cd",
    "pat": "1f933",
    "set": "1f9f0",
    "sip": "1f964",
    "dip": "1f964",
    "din": "1f50a",
    "dim": "1f311",
    "gap": "1f53b",
    "get": "1f4e5",
    "fit": "1f4aa",
    "fun": "1f389",
    "ham": "1f969",
    "hat": "1f9e2",
    "cot": "1f6cc",
    "cut": "2702",
    "pack": "1f9f3",
    "pick": "2617",
    "mix": "1f958",
    "wax": "1f56f",
    "tax": "1f4b8",
    "six": "36-20e3",
    "zip": "1f456",
    "zap": "26a1",
    "zig": "3030",
    "zag": "3030",
    "buzz": "1f41d",
    "fizz": "1f37e",
    "jazz": "1f3b7",
    "fuzz": "1f9f6",
    "whizz": "1f4a8",
    "puff": "1f4ad",
    "huff": "1f4a8",
    "cuff": "1f9e3",
    "sniff": "1f443",
    "stuff": "1f9f3",
    "chat": "1f4ac",
    "chop": "1f52a",
    "rich": "1f4b0",
    "ring": "1f48d",
    "rip": "1f9f6",
    "rug": "1f9f1",
    "run": "1f3c3",
    "lap": "1f9b5",
    "let": "1f91d",
    "lid": "1f373",
    "log": "1fab5",
    "job": "1f4bc",
    "jog": "1f3c3",
    "jug": "1f964",
    "kim": "1f9d1",
    "kit": "1f9f0",
    "can": "1f96b",
    "cup": "2615",
    "vet": "1f3e5",
    "vat": "1f9c3",
    "vim": "26a1",
    "wag": "1f436",
    "win": "1f3c6",
    "wet": "1f4a6",
    "web": "1f578",
    "well": "1f4a7",
    "have": "1f91d",
    "near": "1f3af",
    "year": "1f4c5",
    "yell": "1f4e2",
    "yet": "23f3",
    "yap": "1f436",
    "quit": "1f6d1",
    "quick": "1f407",
    "quack": "1f986",
    "quiz": "1f4dd",
    "quilt": "1fa48",
    "pair": "1f45f",
    "hair": "1f487",
    "fair": "1f3a0",
    "chair": "1fa91",
    "stairs": "1fa9c",
    "wait": "23f3",
    "sail": "26f5",
    "tail": "1f43e",
    "train": "1f682",
    "rain": "1f327",
    "pain": "1fa7a",
    "light": "1f4a1",
    "night": "1f30c",
    "right": "1f449",
    "fight": "1f94a",
    "high": "1f51d",
    "sight": "1f52d",
    "coat": "1f9e5",
    "boat": "1f6a4",
    "road": "1f6e3",
    "soap": "1f9fc",
    "toad": "1f438",
    "moon": "1f319",
    "food": "1f35d",
    "boot": "1f462",
    "room": "1f6aa",
    "spoon": "1f944",
    "book": "1f4d6",
    "look": "1f440",
    "good": "1f44c",
    "foot": "1f9b6",
    "cook": "1f373",
    "wood": "1fab5",
    "car": "1f695",
    "park": "1f333",
    "farm": "1f33e",
    "star": "1f31f",
    "arm": "1f9b5",
    "jar": "1fad9",
    "fork": "1f374",
    "sport": "26be",
    "burn": "1f525",
    "turn": "1f503",
    "fur": "1f98a",
    "corn": "1f33d",
    "cow": "1f404",
    "now": "1f557",
    "owl": "1f989",
    "down": "1f447",
    "town": "1f3d8",
    "how": "1f914",
    "coin": "1fa99",
    "boil": "1f373",
    "soil": "1f331",
    "point": "1f449",
    "oil": "1fad2",
    "join": "1f50d",
    "ear": "1f442",
    "hear": "1f442",
    "near": "1f90f",
    "year": "1f5d3",
    "dear": "2764",
    "tear": "1f622",
    "air": "2601",
    "hair": "1f9b1",
    "pen": "270f",
    "ten": "1f51f",
    "hen": "1f413",
    "net": "1f945",
    "bed": "1f6cc",
    "red": "2764",
    "duck": "1f986",
    "sock": "1f9e6",
    "pick": "1f3c3",
    "pack": "1f392",
    "kick": "1f45f",
    "neck": "1f9b5",
    "sun": "1f31e",
    "bus": "1f68d",
    "mug": "2615",
    "bun": "1f369",
    "bat": "1f987",
    "big": "2b06",
    "fan": "1f4a8",
    "fog": "1f32b",
    "fit": "1f4aa",
    "fun": "1f3a8",
    "off": "1f51c",
    "bag": "1f392",
    "ham": "1f356",
    "hat": "1f3a9",
    "hot": "2615",
    "hit": "1f4a2",
    "hop": "1f998",
    "pin": "1f4cc",
    "pan": "1f943",
    "man": "1f468",
    "map": "1f30d",  # глобус-карта, не NASA
    "mat": "1f9fa",
    "nap": "1f4a4",
    "and": "0026",
    "sand": "23f3",
    "dog": "1f415",
    "dig": "1f5ff",
    "pot": "1f3fa",
    "top": "1f9e9",
    "cot": "1f476",
    "cat": "1f408",
    "cap": "1f9e2",
    "kid": "1f476",
    "milk": "1f95b",
    "park": "1f3de",
    "sit": "1fa91",
    "sip": "1f375",
    "sad": "1f61e",
    "set": "1f4e6",
    "tin": "1f6e2",
    "tap": "1f6bf",
}

EMOJI["ten"] = "1f51f"
EMOJI["sun"] = "1f31e"
EMOJI["map"] = "1f5fa"
EMOJI["cat"] = "1f431"
EMOJI["dog"] = "1f436"

# Как произносить звук вслух (английский TTS / say)
SPEAK_SOUND: dict[str, str] = {
    "s": "sss",
    "a": "a",
    "t": "t",
    "p": "p",
    "i": "i",
    "n": "nnn",
    "m": "mmm",
    "d": "d",
    "g": "g",
    "o": "o",
    "c": "k",
    "k": "k",
    "ck": "k",
    "e": "e",
    "u": "u",
    "r": "rrr",
    "h": "hhh",
    "b": "b",
    "f": "fff",
    "ff": "fff",
    "l": "lll",
    "ll": "lll",
    "ss": "sss",
    "j": "j",
    "v": "vvv",
    "w": "w",
    "x": "ks",
    "y": "y",
    "z": "zzz",
    "zz": "zzz",
    "qu": "kw",
    "ch": "ch",
    "sh": "shh",
    "th": "th",
    "ng": "ng",
    "ai": "ay",
    "ee": "ee",
    "igh": "eye",
    "oa": "oa",
    "oo": "oo",
    "ar": "ar",
    "or/ur": "or",
    "ow": "ow",
    "oi": "oy",
    "ear": "ear",
    "air": "air",
    "s-a-t-p": "sat",
    "i-n-m-d": "pin",
    "g-o-c-k": "dog",
    "ck-e-u-r": "red",
    "h-b-f": "hat",
    "l-s": "bell",
    "ff-ll-ss": "bell",
    "j-v-w-x": "fox",
    "y-z-qu": "yes",
    "ch-sh-th-ng": "ship",
    "ai-ee-igh-oa": "rain",
    "oo-ar-or": "car",
    "ow-oi-ear-air": "cow",
    "review": "read",
    "stories": "the fox",
}


def twemoji_url(code: str) -> str:
    return f"https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/{code}.svg"


# Только то, что ребёнок узнает на фото. Остальное — текст, не случайная корова с Википедии.
PICTURE_OK = frozenset({
    "hello", "hi", "fox", "foxy", "yes",
    "mum", "dad", "sister", "brother", "baby", "family", "friend",
    "cat", "dog", "bird", "fish", "pet", "pig", "duck", "hen", "rat", "cow", "owl",
    "bee", "yak", "bat",
    "bag", "book", "pen", "pencil", "rubber", "ruler", "case", "desk", "bed", "chair",
    "lamp", "room", "door", "box", "ball", "doll", "car", "train", "toy", "bus", "school",
    "apple", "banana", "milk", "cake", "bread", "egg", "ham", "jam", "cup", "mug", "pot",
    "pan", "hat", "cap", "sock", "coat", "vest",
    "red", "blue", "green", "yellow", "black", "white",
    "sun", "moon", "star", "tree", "rain", "park", "farm", "hill", "boat", "ship",
    "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
    "happy", "sad", "smile", "cry",
    "run", "jump", "sit", "eat", "drink", "play", "sleep", "stop",
    "big", "small",
    "map", "mat", "pin", "net", "man", "kid", "bell", "log", "leg", "lip", "fan",
    "van", "web", "zip", "zoo", "queen", "king", "ring", "shop", "ship", "fish",
    "chip", "chin", "rain", "tail", "road", "soap", "loaf", "spoon", "fork", "jar",
    "arm", "ear", "hair", "stairs", "coin", "oil", "town", "night", "light", "food",
    "boot", "foot", "wood", "corn", "fur",
})

TEACH_RU = {
    "name": "Как тебя зовут? Скажи: My name is … и своё имя.",
    "i": "Так говорят только про себя. Дальше почти всегда am.",
    "am": "Маленький мостик после I. Без него фраза не собирается: I am …",
    "you": "Так зовём того, кто рядом. Не про себя.",
    "no": "Когда не согласен. Часто вместе: No, thank you.",
    "yes": "Когда согласен. Коротко кивни и скажи вслух.",
    "have": "Когда что-то есть у тебя. I have a bag.",
    "has": "То же, что have, но про него или её.",
    "where": "Вопрос «где?». Where is the cat?",
    "what": "Вопрос «что?».",
    "who": "Вопрос «кто?».",
    "how": "Вопрос «как?».",
    "when": "Вопрос «когда?».",
    "why": "Вопрос «почему?».",
    "can": "Умею, могу. I can run. Это не банка.",
    "like": "Нравится. I like cake.",
    "please": "Вежливое слово, когда просишь.",
    "thanks": "Короткое спасибо.",
    "thank": "Полное спасибо: thank you.",
    "in": "Внутри. The cat is in the box.",
    "on": "На поверхности. The book is on the desk.",
    "under": "Под. The ball is under the bed.",
    "up": "Вверх.",
    "off": "Прочь или выключено.",
    "and": "Соединяет двух: mum and dad.",
    "or": "Или одно, или другое.",
    "if": "Если.",
    "it": "Про вещь или животное, не про человека.",
    "this": "Вот это, рядом. This is my bag.",
    "that": "Вон то, дальше.",
    "let": "Давай: Let us play!",
    "get": "Взять или получить.",
    "see": "Видеть. I see a fox.",
    "look": "Смотри сюда! Look! A bird!",
    "count": "Считай: one, two, three.",
    "number": "Число. One — тоже number.",
    "fun": "Когда весело.",
    "yum": "Когда еда вкусная.",
    "good": "Хорошо. Good job!",
    "bad": "Плохо.",
    "hungry": "Хочется есть. I am hungry.",
    "thirsty": "Хочется пить. I am thirsty.",
    "now": "Сейчас.",
    "down": "Вниз.",
    "go": "Идти, поехали.",
    "play": "Играть. Let's play — зовём начать.",
    "red": "Покажи красное и скажи: It is red.",
    "blue": "Покажи синее: It is blue.",
    "green": "Как трава. The grass is green. Скажи: It is green.",
    "yellow": "Как солнце. The sun is yellow.",
    "black": "Тёмный цвет. It is black.",
    "white": "Светлый цвет. It is white. Без русского «х» в начале.",
    "pet": "Кто живёт дома с тобой. This is a pet. Foxy — fox, не типичный pet.",
    "cat": "Покажи кота: This is a cat.",
    "dog": "Покажи собаку: This is a dog.",
    "bird": "В небе или в клетке: This is a bird.",
    "fish": "В воде: This is a fish.",
    "mum": "Покажи маму: This is my mum.",
    "dad": "Покажи папу: This is my dad.",
    "happy": "Улыбнись и скажи: I am happy.",
    "sad": "Грустное лицо: I am sad.",
}

# Фраза на карточке, только если это не само слово ещё раз.
PHRASE = {
    "name": ("My name is Foxy.", "Меня зовут Foxy."),
    "i": ("I am Foxy.", "Я — Foxy."),
    "am": ("I am Foxy.", "Я — Foxy."),
    "you": ("You are a kid.", "Ты ребёнок."),
    "no": ("No, thank you.", "Нет, спасибо."),
    "yes": ("Yes, I am.", "Да."),
    "have": ("I have a bag.", "У меня есть сумка."),
    "can": ("I can run.", "Я умею бегать."),
    "like": ("I like cake.", "Мне нравится торт."),
    "please": ("Yes, please.", "Да, пожалуйста."),
    "thanks": ("Thanks!", "Спасибо!"),
    "thank": ("Thank you.", "Спасибо."),
    "where": ("Where is the cat?", "Где кошка?"),
    "hello": ("Hello!", "Привет!"),
    "hi": ("Hi!", "Привет!"),
}


def teach_line(en: str, ru: str = "") -> str:
    key = (en or "").lower()
    if key in TEACH_RU:
        return TEACH_RU[key]
    ph, _ = phrase_for(en, ru)
    if ph and ph.lower() != key:
        return f"Не перевод. Скажи как Foxy: {ph}"
    return "Смотри картинку. Скажи слово. Перевод не зубри."


_COLOUR = frozenset({"red", "blue", "green", "yellow", "black", "white", "brown", "orange", "pink", "grey", "gray"})
_ANIMAL = frozenset({"cat", "dog", "bird", "fish", "pet", "fox", "pig", "duck", "hen", "rat", "cow", "owl", "bee"})
_FAMILY = frozenset({"mum", "dad", "sister", "brother", "baby"})
_FEEL = frozenset({"happy", "sad", "hungry", "thirsty"})
_SIZE = frozenset({"big", "small"})
_NUM = frozenset({"one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"})


def _art(word: str) -> str:
    return "an" if (word[:1] in "aeiou") else "a"


def phrase_for(en: str, ru: str = "") -> tuple[str, str]:
    key = (en or "").lower()
    hit = PHRASE.get(key)
    if hit:
        return hit[0], ""
    if key in _COLOUR:
        return f"It is {key}.", ""
    if key in _FEEL:
        return f"I am {key}.", ""
    if key in _SIZE:
        return f"It is {key}.", ""
    if key in _NUM:
        return f"I see {key}.", ""
    if key == "family":
        return "This is my family.", ""
    if key in _FAMILY:
        return f"This is my {key}.", ""
    if key in _ANIMAL:
        return f"This is {_art(key)} {key}.", ""
    if key.isalpha() and len(key) > 2:
        return f"This is {_art(key)} {key}.", ""
    return en, ""


# Служебные слова: не подставляем случайное фото.
NEVER_PICTURE = frozenset({
    "name", "i", "am", "you", "no", "have", "has", "where", "what", "who", "how",
    "when", "why", "can", "like", "please", "thanks", "thank", "in", "on", "under",
    "up", "off", "and", "or", "if", "it", "this", "that", "let", "get", "see",
    "look", "count", "number", "fun", "yum", "good", "bad", "hungry", "thirsty",
    "now", "down", "go", "a", "an", "the", "is", "are", "my", "your",
})

# Вики-дамп по английскому слову часто врёт (six=камера, dad=икона). Не показываем.
REJECT_PHOTO = frozenset({
    "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
    "hello", "hi", "mum", "dad", "sister", "brother", "baby", "family", "friend",
    "play", "game", "school", "jump", "sit", "toy", "happy", "sad", "smile", "cry",
    "red", "blue", "green", "yellow", "black", "white",
})

# Учитель Foxy, не полицейский и не дикий зверь как персонаж.
BRAND_ART = {
    "hello": "/world/foxi/wave.png",
    "hi": "/world/foxi/wave.png",
    "foxy": "/world/foxi/cheer.png",
}

# Нет своего jpg — берём соседнее реальное фото того же смысла.
PHOTO_ALIAS = {
    "eat": "apple",
    "yum": "apple",
    "hat": "cap",
    "cup": "mug",
    "nap": "bed",
    "sleep": "bed",
    "boat": "ship",
    "pet": "cat",
    "thirsty": "drink",
    "sip": "drink",
    # фирменные карточки закрывают соседние слова того же смысла
    "foot": "boot",
    "room": "door",
    "hear": "ear",
    "sing": "song",
    "hit": "bat",
    "run": "jog",
    "less": "fill",
    "set": "dish",
    "pair": "sock",
    "stairs": "hill",
    "fuzz": "fur",
    "yap": "dog",
    "yell": "song",
    "yak": "cow",
    "wow": "fan",
    "vim": "fit",
    "vat": "pot",
    "vest": "coat",
    "tear": "rain",
    "whizz": "zap",
    "zig": "zip",
    "zag": "zip",
    "quiz": "quilt",
    "boss": "desk",
    "pat": "cat",
    "sat": "mat",
    "jug": "mug",
    "turn": "top",
    "join": "ring",
    "yet": "egg",
}


def _photo_file(slug: str) -> str:
    if not slug:
        return ""
    root = Path(__file__).resolve().parents[3] / "world" / "public" / "learn" / "words"
    for ext in (".jpg", ".webp", ".png"):
        path = root / f"{slug}{ext}"
        if path.exists() and path.stat().st_size > 8000:
            return f"/learn/words/{slug}{ext}"
    return ""


def shows_picture(en: str) -> bool:
    return bool(image_path(en))


def image_path(en: str) -> str:
    slug = "".join(ch for ch in (en or "").lower() if ch.isalnum())
    if slug in NEVER_PICTURE:
        return ""
    brand = BRAND_ART.get(slug, "")
    if brand:
        return brand
    if slug in REJECT_PHOTO:
        return ""
    hit = _photo_file(slug)
    if hit:
        return hit
    alias = PHOTO_ALIAS.get(slug, "")
    if alias in REJECT_PHOTO:
        return ""
    return _photo_file(alias)
